### ISSUE TITLE
Update readme to document new build and installer

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#109]
The current readme sections on Installation, Builds and RevitLookup.Installation are obsolete, and the new build and installer are undocumented.

**Comment by Nice3point** [comment]
Ok, I will prepare quick edits

**Comment by Nice3point** [comment]
Do you want to store files Wishlist.md and Changelog.md in the Doc folder?

**Comment by Nice3point** [comment]
If you need to document something else, write about it here

**Comment by jeremytammik** [comment]
i think this is complete now :-) thank you ever so much for all your untiring support!
