### ISSUE TITLE
Duplication of Parameters

### ISSUE THREAD

**Issue by RevitArkitek** [jeremytammik/RevitLookup#11]
Hello,
I've noticed that there are parameters that get duplicated, especially when using the Snoop Active View tool.  Then clicking on < ParameterSet>.  It also happens with some of the parameters in elements as well.  I have the same problem in a couple of my addins after recompiling in 2016 and not sure what's causing it.  Thanks.

**Comment by jeremytammik** [comment]
hi there. i think that this is due to the fact that the BuiltInParameter enumeration uses explicit hard-coded values, and some of them are duplicated. i have run into this in the past, many times. in what way is it a problem for you?

**Comment by RevitArkitek** [comment]
In the parameter list, it seems strange to have a lot of the parameters show up twice since it hasn't happened before.  In a combobox for a user I could just check for duplicates before adding them.  Thanks.

**Comment by jeremytammik** [comment]
yes, you should definitely not allow this to happen in your user interface. please be aware that different parameters can have the same UI display name as well.
