### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by Nice3point** [jeremytammik/RevitLookup#111]
@jeremytammik can you create a new 'develop' branch? The idea is this: accept pull requests only in this branch, test new functions, and if everything is fine, merge with the main 'master'. I would also disable the creation of an installer for this branch, leaving only compilation. This will keep the 'master' branch always in the correct state

**Comment by jeremytammik** [comment]
i created a `dev` branch. i do not know how to use it yet.   :-)

**Comment by jeremytammik** [comment]
still practicing this myself...
