### ISSUE TITLE
modeless mode for revit <2022 - installer issue?

### ISSUE THREAD

**Issue by jmcouffin** [jeremytammik/RevitLookup#112]
hi @jeremytammik and  @Nice3point and @NeVeSpl 
I tried the installer as per readme instructions and noticed it worked well except the modeless mode is available only in revit 2022 after installation.
I cannot find if it is expected or an issue:
- is my install messed up?
- is the modelless mode implemented only in 2022?
- is it due to compilation of the wrong code by the git actions or the installer?

**Comment by Nice3point** [comment]
only the latest revit version is supported by the project, the modeless window was added in the 22nd version, it will not be in previous versions

**Comment by Nice3point** [comment]
I can enable legacy support, but this will increase the size of the code and complicate development. Only @jeremytammik  can decide whether to support past versions. In previous Issues, they decided to abandon this.

**Comment by jeremytammik** [comment]
I would advise against supporting previous versions. This is first and foremost a developer tools. No bells and whistles.

**Comment by jmcouffin** [comment]
Damned! I like 🔔 and 
![image](https://user-images.githubusercontent.com/7872003/140105338-af6573f0-1bac-4477-92c7-06a513775b81.png)
@jeremytammik it is not just a developer tool. I use it during project and show how to use it to get the most out of revit when you hit the wall of OOTB tools. Just an example, when you want to get the id and then be anle to select face based faimly hosts...

**Comment by jeremytammik** [comment]
Yes, sorry about that. Obviously, if anyone is willing to add yet more bells and whistles, the modeless functionality is possible in previous releases as well. However, as pointed out above, it would very significantly increase complexity. I am surprised and impressed and above all grateful that @NeVeSpl was able and willing to implement this feature at all!

**Comment by Nice3point** [comment]
@jmcouffin you can download the source code, change the revit version variable here https://github.com/jeremytammik/RevitLookup/blob/master/RevitLookup/RevitLookup.csproj#L21 and here https://github.com/jeremytammik/RevitLookup/blob/master/RevitLookup/RevitLookup.csproj#L42 compile the project and get a modeless window for the desired Revit version

**Comment by jmcouffin** [comment]
Thanks for pointing that out @Nice3point 
@jeremytammik maybe including this info in the Readme would be a + ?

**Comment by Nice3point** [comment]
I think this is obvious information for developers

**Comment by jmcouffin** [comment]
But not so obvious to architecture trained people like me without some (if not a lot) of tinkering.
The whole autodesk software environment tends to empower end users with some coding up to a certain point (Dynamo, LISP in Autocad, ...)... so... empower us properly 😸 !
