### ISSUE TITLE
Error with snoop family from Project Browser

### ISSUE THREAD

**Issue by chuongmep** [jeremytammik/RevitLookup#113]
Dear JeremyTammik,
I recently came across some important updates in this source code, but they are still persisting this bug on the recent new version, please take a look.
![image](https://user-images.githubusercontent.com/31106432/140088568-9b5bba77-8a16-4935-a458-2044d4632509.png)
Video demo error :
https://user-images.githubusercontent.com/31106432/140087691-1863fb00-a6c2-4e87-8ac7-ffe7d5bcab41.mp4

**Comment by Nice3point** [comment]
@jeremytammik 
https://github.com/jeremytammik/RevitLookup/blob/master/RevitLookup/Snoop/Selectors.cs#L70
the problem is in this line because the selected item in the video is a type and the "WhereElementIsNotElementType ()" method returns instances

**Comment by Nice3point** [comment]
It would be nice to remove this filter and replace ids.Any () with ids.Count> 0. This will improve performance as Any creates a new Enumerator

**Comment by NeVeSpl** [comment]
Sorry for that, indeed I have made mistake.

Regarding performance, code readability and semantic meaning are more important than performance in places where performance does not matter.

**Comment by Nice3point** [comment]
![изображение](https://user-images.githubusercontent.com/20504884/140128200-22e79193-55ec-41e4-96c1-69f864e21231.png)
I agree that sometimes code readability is more important, but in this case additional lines or conditions are not added. And here is the difference in speed 1200 times with memory allocation = (

**Comment by jeremytammik** [comment]
wow, impressive! thank you for the conclusive benchmark. i'll add a note of that result to the blog, i think.

**Comment by NeVeSpl** [comment]
It takes 27 NANO seconds, and 40 Bytes in instruction that is invoked only once per use case 🤣. It really does not matter.

**Comment by Nice3point** [comment]
I only advise using properties instead of methods when possible. Any() is for IEnumerable when the number of elements is unknown and the Count property is not available

**Comment by chuongmep** [comment]
Yes,use count is possible in this case.

**Comment by Nice3point** [comment]
@NeVeSpl thanks!

**Comment by chuongmep** [comment]
Fast and accurate solution, thanks a lot.
