### ISSUE TITLE
Couldn´t find the msi installer for latest version

### ISSUE THREAD

**Issue by arqn** [jeremytammik/RevitLookup#116]
Hi;
I couldn´t find the latest version .msi installer, instead, I have found the version installer for revit 2021.

Am I doing something wrong or maybe from version 2022 the installation process changes?

Thanks for all

**Comment by Nice3point** [comment]
![изображение](https://user-images.githubusercontent.com/20504884/140732361-4bdbadbc-9360-4108-b175-cc716d1f445b.png)

Hi, did you download this file according to the instructions in the Readme?

The installer contains the latest version 2022, check this path `%APPDATA%\Autodesk\Revit\Addins\2022`, does it contain these files?
![изображение](https://user-images.githubusercontent.com/20504884/140732569-81f9af8c-bbee-4477-b88d-25fb677f6ad2.png)

**Comment by Nice3point** [comment]
@ricaun ProductVersion and FileVersion are dll properties, not MSI, which versions do you mean? The installer has its own product version and it is displayed in the Windows control panel.
![изображение](https://user-images.githubusercontent.com/20504884/141192673-c13b604b-1e84-46ee-884b-1e31a094da86.png)

**Comment by ricaun** [comment]
I never use MSI so I did not know MSI does not have ProductVersion and FileVersion.

I want to use some PowerShell to get the version on the workflow and apply it to the Release tag and name.

I found this: https://technotes.khitrenovich.com/check-msi-version-powershell/ 

Looks promising...

**Comment by Nice3point** [comment]
aren't you considering creating a release through Nuke? you can set the task of creating a release after creating the installer https://www.ariank.dev/create-a-github-release-with-nuke-build-automation-tool/

**Comment by ricaun** [comment]
Interesting, I didn't know it is possible using Nuke.
By de look you need to mess with GithubRepositoryAuthToken, I don't want that...
I already have a workflow that send the artifact files to the release.
Only need to to find a better way to check the compiled version.

**Comment by Nice3point** [comment]
I'll think about it, maybe there's an option to do it with Nuke. And remove the publication of artifacts. If it doesn't work out, there are a couple of ideas to do using Yml

**Comment by Nice3point** [comment]
@ricaun it is possible to pass $ {{secrets.GITHUB_TOKEN}} as a parameter for Nuke, but I did not find where to use it, apparently authorization is needed. Within YML, you can use Regex in the output directory, the file name contains the version number, also the MSI file has a Version property, you can use it

**Comment by ricaun** [comment]
> 
> 
> @ricaun it is possible to pass $ {{secrets.GITHUB_TOKEN}} as a parameter for Nuke, but I did not find where to use it, apparently authorization is needed. Within YML, you can use Regex in the output directory, the file name contains the version number, also the MSI file has a Version property, you can use it

Probably is possible to use the environment variable, is possible to set on the YML and then consume inside the nuke, need to test but I believe should work.

My release test works! :)

![image](https://user-images.githubusercontent.com/12437519/141352534-9299cd54-b90e-475e-977b-21dcb9d4d027.png)

I set some environment variables to set the repository name and version release.

**Comment by Nice3point** [comment]
Nice! try to get the version number from the name of the MSI file, it is generated in the **output** folder, which is located at the root of the solution.
![изображение](https://user-images.githubusercontent.com/20504884/141353037-c825db7e-847f-4f27-a733-7087b7d4a918.png)

**Comment by ricaun** [comment]
> 
> 
> Nice! try to get the version number from the name of the MSI file and set the env var, it is generated in the output folder, which is in the root of the solution. ![изображение](https://user-images.githubusercontent.com/20504884/141353037-c825db7e-847f-4f27-a733-7087b7d4a918.png)

I gonna use this ps1 script:

``` ps1
###############################################################
# Name:         GetMsiVersion.ps1
# Description:  Prints the largest version of the MSI files installer
# Usage:        .\GetMsiVersion.ps1 .\*.msi
# Original:     http://stackoverflow.com/q/8743122/383673
###############################################################

param (
    [string]$path
)

try {
    $version = [System.Version]::Parse("0.0.0.0")
    Get-ChildItem –Path $path | 
    Foreach-Object {
        $MSI = $_
        $windowsInstaller = New-Object -com WindowsInstaller.Installer
        $database = $windowsInstaller.GetType().InvokeMember(
            "OpenDatabase", "InvokeMethod", $Null,
            $windowsInstaller, @($MSI.FullName, 0)
        )
 
        $q = "SELECT Value FROM Property WHERE Property = 'ProductVersion'"
        $View = $database.GetType().InvokeMember(
            "OpenView", "InvokeMethod", $Null, $database, ($q)
        )
 
        $View.GetType().InvokeMember("Execute", "InvokeMethod", $Null, $View, $Null)
        $record = $View.GetType().InvokeMember( "Fetch", "InvokeMethod", $Null, $View, $Null )
        $productVersion = $record.GetType().InvokeMember( "StringData", "GetProperty", $Null, $record, 1 )

        $versionFile = [System.Version]::Parse($productVersion) 
        if ($versionFile -gt $version) 
        {
            $version = $versionFile    
        }
    }
    return $version.toString()
} catch {
    throw "Failed to get MSI file version: {0}." -f $_
}
```

Some code like this `$version = .\Build\GetMsiVersion.ps1 .\output\*`

**Comment by Nice3point** [comment]
` $q = "SELECT Value FROM Property WHERE Property = 'ProductVersion'"`
this line won't work
try use this https://stackoverflow.com/questions/48409026/powershell-extract-number-from-file-name
Regex (\d+.)+\d+
![изображение](https://user-images.githubusercontent.com/20504884/141358498-d2a8942f-a37f-4445-830d-5aa3763205e8.png)

**Comment by Nice3point** [comment]
param ([string]$path)
    
Get-ChildItem $path | where {$_.extension -eq ".msi"} | Where{$_.Name -match '(\d+.)+\d+'} | ForEach{return $Matches[0]}

**Comment by Nice3point** [comment]
add an exception if possible if the result of the script is string.Empty to cancel the creation of the release

**Comment by ricaun** [comment]
> 
> 
> ` $q = "SELECT Value FROM Property WHERE Property = 'ProductVersion'"` this line won't work try use this https://stackoverflow.com/questions/48409026/powershell-extract-number-from-file-name Regex (\d+.)+\d+ ![изображение](https://user-images.githubusercontent.com/20504884/141358498-d2a8942f-a37f-4445-830d-5aa3763205e8.png)

Strange the `GetMsiVersion.ps1` is working fine on workflow runs.

I don't like the idea to read the file name to get the version, if the file name change for some reason could cause some issue.

**Comment by Nice3point** [comment]
less code, less errors, faster script execution)
The version in the file name and the installer property are taken from one variable. I don't think the style of the filename will change anytime soon.

**Comment by Nice3point** [comment]
@ricaun I did it 🤯🥳  I created a Release via Nuke, for authorization it is sufficient to pass $ {{secrets.GITHUB_TOKEN}} as an argument.
 
![изображение](https://user-images.githubusercontent.com/20504884/141642680-b00530bd-f360-40f1-b619-b7a4e1cf4331.png)

Writing in C # is much better than in YML. It remains to automate the receipt of the version number and add a Changelog, I am thinking of getting it from the Changelog.md file.

**Comment by ricaun** [comment]
Nice! Yes c# is much easy to work with.

How are you passing the `${{secrets.GITHUB_TOKEN}} `, I was testing using Environment Variables and works.

YML
``` yml
      - name: Run './Build/build.cmd '
        run: ./Build/build.cmd 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

C#
```C#
Environment.GetEnvironmentVariable("GITHUB_TOKEN")
```

The version number is equal to the version number and the tag is equal to the DLL version, which is how Jeremy is using.

Using the `Changelog.md` file is a great idea, I don't know if you are adding Release with the `CreatePackage.yml ` or a separated workflow_dispatch. If a Release already exists with the same tag could cause some error, but in C# probably is easy to delete, rename and do everything you want.

**Comment by Nice3point** [comment]
![изображение](https://user-images.githubusercontent.com/20504884/141643887-e0d4e015-3a6d-4889-8fe1-4d3e7047c60c.png)
![изображение](https://user-images.githubusercontent.com/20504884/141644065-4208a636-8f97-4376-9049-a572b64577b2.png)

All tags can be obtained from this place (screenshot below), find the largest version, check that the new version is older than the one found and does not coincide with the existing ones. In the case when attempts to create a release with an existing tag, the release will be created, but the Draft properties will remain true:
![изображение](https://user-images.githubusercontent.com/20504884/141643962-2f9db4ae-3637-4e08-bd21-f0ed332851f6.png)
I will finalize the code one of these days

**Comment by ricaun** [comment]
Woooo Nuke is really powerful, I was looking to check how to sign files using Nuke.

I don't know exactly what `[Secret]` does in front of the `[Parameter]` but by looking at common attribute in token/password parameter.

**Comment by Nice3point** [comment]
There are many examples in the Nuke repository, for example this one, apparently they sign their package here https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Components/ISignPackages.cs

**Comment by Nice3point** [comment]
Hmm, maybe the Secret attribute encrypts the debugging parameter, they don't know why it is needed, gitAction does it itself, and replaces everything with asterisks

**Comment by Nice3point** [comment]
@ricaun  🥳🥳🥳
![изображение](https://user-images.githubusercontent.com/20504884/141649107-f0bc7f41-e65c-462f-aa87-2f7f79b56dc2.png)
on the test project everything works, the changelog supports, the multi-line version is the same, now I will send a PR for discussion, maybe something else needs to be fixed

**Comment by Nice3point** [comment]
@arqn  https://github.com/jeremytammik/RevitLookup#build
