### ISSUE TITLE
Error when snoop symbol geometry cad link

### ISSUE THREAD

**Issue by chuongmep** [jeremytammik/RevitLookup#117]
Image Problem :
![image](https://user-images.githubusercontent.com/31106432/140769122-4b9df791-0d9d-4f29-8943-dc658dd8e0de.png)
File sample :
[Drawing1.zip](https://github.com/jeremytammik/RevitLookup/files/7498081/Drawing1.zip)
[revitfile.zip](https://github.com/jeremytammik/RevitLookup/files/7498177/revitfile.zip)
Step by step  :
1. Click to **Symbol** and click ok
![image](https://user-images.githubusercontent.com/31106432/140770030-8cba77ec-d6f0-48f5-8df7-7e6525907b90.png)
 2. Click to **SymbolGeometry**

![image](https://user-images.githubusercontent.com/31106432/140770122-338e9c43-adfe-44c4-9679-604c5937ef8c.png)
Video :
https://user-images.githubusercontent.com/31106432/140770842-480dc41e-ffab-46bd-8d68-f3e3b378344f.mp4

**Comment by Nice3point** [comment]
![изображение](https://user-images.githubusercontent.com/20504884/140797594-24b8693b-18ba-4f61-930c-cb41797532d7.png)

**Comment by jeremytammik** [comment]
The `Arc` object is a pure memory-only geometry object. It is not a database resident Revit `Element`. Therefore, the RevitLookup code should not allow it to be snooped as if it were. -- https://www.revitapidocs.com/2022/1f5f541e-9335-aef3-0e75-59eed9ae2221.htm -- Something is wrong with the snoop routing. It should terminate before drilling down into the geometry objects, or treat them differently than the database elements derived from the `Element` base class.

**Comment by Nice3point** [comment]
Fixed ![изображение](https://user-images.githubusercontent.com/20504884/146970805-d221fe3f-ebcb-4576-adc9-14441ee859d6.png)

Exceptions are now displayed correctly. The very throwing of the exception is caused by the fact that the object is unloaded from memory when you call another method. I just ran into this when I was developing my plugin. This is how the get_Geometry () method works.

Also, when throwing an exception, the error message is taken from the nested one, instead of the wrapping one.

**Comment by Nice3point** [comment]
Finally, the error messages will be more informative 🙃

![изображение](https://user-images.githubusercontent.com/20504884/146974600-460277dc-6580-4765-a4c5-af68d8c6e301.png)

**Comment by Nice3point** [comment]
@jeremytammik can you set the dev branch by default? its content will be displayed on the github page, it makes sense since it is updated more often
![изображение](https://user-images.githubusercontent.com/20504884/146974762-c98dc1c3-5667-47b2-adbc-355260e11fe5.png)

**Comment by Nice3point** [comment]
@jeremytammik have you read the message about the license for JetBrains (analogue of Visual Studio) in the mail?) if you don't need them, we can gift it to one of the contributors to this project for the new year)

**Comment by jeremytammik** [comment]
@Nice3point  yes, sure, thank you for the good suggestion! done.

**Comment by jeremytammik** [comment]
> error messages will be more informative

wow, brilliant! very useful feature! strong didactical learning support :-)
