### ISSUE TITLE
NukePipeline.yml ArgumentException

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#119]
This error was caused by me:

NukePipeline.yml: All jobs have failed: ArgumentException: The repository already contains a Release with the tag: 2022.0.2.5

I edited readme directly in the master branch.

Apparently, that causes a new release to be generated, but the release is already present.

I guess I can solve it by updating the release number in the `dev` branch.

Maybe I should try that to fix the error.

This is just trial and error, though, fishing in the dark...

**Comment by jeremytammik** [comment]
followed the steps described by @Nice3point to generate a new release and hoping that will resolve the error:

https://thebuildingcoder.typepad.com/blog/2021/11/installer-asset-formit-and-quaterions.html#3

Sorry for the mishap.

**Comment by Nice3point** [comment]
Hi Jeremy, if you need to update only Readme.md , or some other minor file, it's okay if Pipeline fails with an error. you can ignore it. Such edits do not need to upgrade the project version. But I'm glad that you managed to create the release yourself)

**Comment by jeremytammik** [comment]
Yes, creating the new release was very easy following your instructions. So, in future, if such an error occurs, I can simply ignore it, and the existing latest release will continue working unaffected? That is a relief!

**Comment by Nice3point** [comment]
just remember that all changes to the master branch start the pipeline and create a release, so it's best to make changes only in the dev branch, and merge with the master only once, before the release itself

**Comment by jeremytammik** [comment]
Yes, understood. And now experienced live, in real life.
