### ISSUE TITLE
Unused  code

### ISSUE THREAD

**Issue by Nice3point** [jeremytammik/RevitLookup#120]
Hi, there is unused code and windows in the application.
![изображение](https://user-images.githubusercontent.com/20504884/144600351-f88c34d6-c5d3-4b83-bb8f-d4d8ba8a2e72.png)
![изображение](https://user-images.githubusercontent.com/20504884/144600373-95846421-b563-495e-9574-c4020551cb97.png)
When opening Revit, there is a subscription to events if the subscription is already subscribed. This condition will never be met.

```c#
if (EventsForm.DocEvents.AreEventsEnabled) EventsForm.DocEvents.EnableEvents(args.Document);
```

If this code is already deprecated, I could remove it. This is still a database exploration add-in, not an example of event usage in Revit.

There are also empty files that do not contain anything. for example HostApplication.cs

**Comment by jeremytammik** [comment]
I believe there was once functionality included which enabled switching on and off the event monitoring. That could be useful to understand the API. It could actually also be a useful and valuable database exploration tool, because: if I perform a manual action in Revit and add a new object or remove an existing one, it may cause more than one new element to be affected. The `DocumentChanged` event enable tracking those via the `added` and `removed` lists. On the other hand, you are right, there are other tools that also enable this, e.g., the element lister, and it makes sense to keep things simple. So, I guessa removing it will do no harm. Removing the empty filers definitely won't :-) Thank you for noticing and pointing it out!

**Comment by Nice3point** [comment]
I understand, but now this option is inactive and not used) That is why I asked the question, should this code be removed or left for the future?)

**Comment by jeremytammik** [comment]
I am completely happy to leave that decision up to you. My impression is that you would prefer to remove it? Correct? If so, that is absolutely fine by me. вялікі дзякуй!

**Comment by Nice3point** [comment]
Not a bad Belarusian speech) I will deal with this closer to the new year) There are also plans to rewrite the code from outdated WinForms to WPF, but this is after the transition of Revit to .Net 5+

**Comment by jeremytammik** [comment]
Cool! The transition will take a while, I'm afraid, but it is being discussed and planned, afaik.

**Comment by Nice3point** [comment]
> discussed and planned.

As far as I understand, the 2023 version will still be on the Net Framework? No details?

**Comment by jeremytammik** [comment]
I have no idea. i know nothing about future versions. This is what i know so far: 

https://thebuildingcoder.typepad.com/blog/2021/01/face-triangulation-lod-net-5-and-core.html#2

**Comment by jeremytammik** [comment]
i could ask for an update from the devteam. i you would like me to do that, please prompt me in the forum:

https://forums.autodesk.com/t5/revit-api-forum/does-revit-target-net-standard/m-p/9792894

**Comment by Nice3point** [comment]
Ok, thanks, I asked a question on the forum

**Comment by jeremytammik** [comment]
thank you, i see it. i'll pass on to the devteam.

**Comment by Nice3point** [comment]
@jeremytammik  hi) can you turn off these checkboxes on the project page so as not to take up extra space?
![изображение](https://user-images.githubusercontent.com/20504884/144709612-a89c0802-07ee-4c16-aa4b-84830ddd4086.png)

And also turn off Wiki, since it is not in use and turn on Discussions (Settings-Options-Features)
![изображение](https://user-images.githubusercontent.com/20504884/144709665-09ff1481-25aa-4540-82a0-cfb532349e25.png)

**Comment by jeremytammik** [comment]
sure, glad to... done.

**Comment by jeremytammik** [comment]
wow, the description of the new release sounds impressive. noticeable speed improvements are not easy to come by! thank you!

**Comment by Nice3point** [comment]
@jeremytammik  check your mail, we got Rider free licenses approved for the project)

**Comment by Nice3point** [comment]
>noticeable speed improvements are not easy to come by

there is still the problem of boxing in object, but this is probably necessary. It takes a long time to rewrite on Generics and may not be realizable, you need to analyze the code that I did not write, this is not an easy task)
