### ISSUE TITLE
minor typo: not visible objects --> non-visible objects

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#126]
cf. the `IncludeNonVisibleObjects` property: https://www.revitapidocs.com/2022/0d277b80-d5e5-1151-d413-b0899da0976f.htm

**Comment by Nice3point** [comment]
@jeremytammik "Undefined View, including non-visible objects" like this?

**Comment by Nice3point** [comment]
updated Release

**Comment by jeremytammik** [comment]
yes, like that.

**Comment by jeremytammik** [comment]
i cannot compile even after installing .net sdk 6. 

the compilation produces 171 errors. 

my installation is:


Microsoft Visual Studio Enterprise 2019
Version 16.11.8
VisualStudio.16.Release/16.11.8+32002.261
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA211
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.94.52318
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.11.94.52318
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.11.21196.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.5.30526.3 Commit Hash:c09c81113bcbc86d57943fcdd67e82434263d61d
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.11.21196.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Profiling support   16.11.21196.2
Profiling support for Python projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by Nice3point** [comment]
![изображение](https://user-images.githubusercontent.com/20504884/147935272-a457cac3-e800-47ca-9888-68195a8bde7e.png)
![изображение](https://user-images.githubusercontent.com/20504884/147935330-cb5de861-ff5e-4fbd-abf5-3c181cef0595.png)
![изображение](https://user-images.githubusercontent.com/20504884/147935433-e0971aa5-9cd0-4eae-950f-deba5131173b.png)
Briefly about the update

**Comment by Nice3point** [comment]
> i cannot compile even after installing .net sdk 6.

Wait, I'll check in my VS

**Comment by Nice3point** [comment]
@jeremytammik  Did you download the SDK from here? https://dotnet.microsoft.com/en-us/download 
![изображение](https://user-images.githubusercontent.com/20504884/147935909-4f11d7b3-25d4-4499-98ec-b43c4532a69e.png)

**Comment by Nice3point** [comment]
it may be that VS 2019 only supports .Net 5 and older. It might be rough, but can you install VS 2022?
