### ISSUE TITLE
document main maintaining author and VS build requirements

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#127]
hi Roman @Nice3point ! Happy New Year to you! Thank you for the new release 2022.0.3.2! I notice that it requires me to install an updated .NET SDK 6.0: It reports error `NETSDK1045`: The current .NET SDK does not support targeting .NET 6.0; Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. I am installing the 6.0 SDK. Maybe this build requirement ought to be mentioned in the readme? In the past, I stuck with a very old version of VS and the SDK, bordering on obsolete, to make sure that absolutely everybody else was more up-to-date than me. Now, we are forcing developers to update their VS and .NET more promptly... I suggest documenting that.

I would also suggest adding you to the `Authors` section, since you are currently the main maintaining author, and I am doing next to nothing at all.

What do you think?

**Comment by Nice3point** [comment]
The current SDK version is listed in the file https://github.com/jeremytammik/RevitLookup/blob/dev/global.json Your VS version doesn't support .Net 6?

**Comment by Nice3point** [comment]
> I would also suggest adding you to the `Authors` section, since you are currently the main maintaining author, and I am doing next to nothing at all.

As you wish) I will continue to support the project. Instead of direct development, you can give ideas, I will implement them

**Comment by jeremytammik** [comment]
nope, not yet... working on it, downloading new sdk...

**Comment by Nice3point** [comment]
I think on the local computer you can change the version to the 5th, everything will work, just in .net 6 Microsoft has made a lot of emphasis on performance. There is also a lot of syntactic sugar, you need to write less code

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/blob/dev/Installer/Installer.cs **.Net 6** style
https://github.com/jeremytammik/RevitLookup/blob/dc3055c439cb46e5ef4c4e24fea6e333fab2c991/Installer/Installer.cs **.Net 5** style

**Comment by Nice3point** [comment]
@jeremytammik .Net 6 support list:
- Visual Studio 2022 (v17.0)
- Visual Studio 2019 for Mac (v8.10)

Try to install VS 2022 or enable SDK preview support
> If you have a preview installed of the requested .NET SDK version, you also need to set the option to enable previews in Visual Studio. Go to Tools > Options > Environment > Preview Features, and make sure that Use previews of the .NET Core SDK is checked.

Microsoft will no longer develop 2019, so this version of the IDE loses its meaning. I might have switched to .Net 6 in vain, it's just that there are no other active developers in the project, so I didn't warn anyone about it. .Net 6 makes my life easier, but if you want to develop the project on the old version of IDE too, I can return .Net 5

**Comment by jeremytammik** [comment]
OK, I'll install VS 2022 next. Might take a day or two, because I have low bandwidth here...

**Comment by chuongmep** [comment]
Hi @Nice3point , 
I have problem with .NET6 , may be problem come from we can't use feature from .NET6 because revit stuck in the version of .NET Framework 4.8, I have test with some load assembly use some feature with **AssemblyLoadContext** in [here ](https://github.com/chuongmep/NET6rRevitAPI/blob/master/ClassLibrary1/SimpleUnloadableAssemblyLoadContext.cs), I think this is just an update to prepare for the future, right?
![image](https://user-images.githubusercontent.com/31106432/149700937-1cbe79e2-e981-4fd1-8dae-6b5506dd40cb.png)

**Comment by Nice3point** [comment]
@chuongmep hi) you can use the features of SDK 6, but to develop the plugin TargetFramework must still be net48 version https://github.com/Nice3point/RevitTemplates/blob/main/Templates/Nice3point.Revit.AddIn/Nice3point.Revit.AddIn.csproj#L7

https://forums.autodesk.com/t5/revit-api-forum/does-revit-target-net-standard/m-p/10814213#M60307

**Comment by chuongmep** [comment]
many thanks, the links are very helpful.

**Comment by jeremytammik** [comment]
no questions, please feel free to close it. thank you!
