### ISSUE TITLE
ParameterBindings Not Correct

### ISSUE THREAD

**Issue by chuongmep** [jeremytammik/RevitLookup#128]
Dear @Nice3point,
I see a problem in here with ParameterBindings. May be is an issue.
![devenv_MUyy5yUguH](https://user-images.githubusercontent.com/31106432/148901897-e6d2335d-ce69-4956-b70a-495765e735b1.png)
Some Code Sample : 
``` cs
 BindingMap bindingMap = DB.Doc.ParameterBindings;
DefinitionBindingMapIterator iterator = bindingMap.ForwardIterator();
            while (iterator.MoveNext())
            {
                Definition def = iterator.Key;
                //TODO SOME THING
            }
```

**Comment by Nice3point** [comment]
I'll see when I get back from work. Apparently support is not implemented, a similar problem on versions 2020 and 2021

**Comment by Nice3point** [comment]
@chuongmep done
![изображение](https://user-images.githubusercontent.com/20504884/149618662-a66ff602-ae0a-4cb7-a38a-c657db639c92.png)
![изображение](https://user-images.githubusercontent.com/20504884/149618671-02d94417-2047-460a-85b4-f1db19e6b86c.png)

**Comment by chuongmep** [comment]
@Nice3point Awesome, Thanks you.
