### ISSUE TITLE
Snoop Loss Method setting from code

### ISSUE THREAD

**Issue by chuongmep** [jeremytammik/RevitLookup#131]
Dear @jeremytammik  and @Nice3point 
Can we add this spreadsheet view, I am working with MEP and I hope they are added to the Revit lookup
I see a link in here, maybe it is not obtained in the usual way : https://adndevblog.typepad.com/aec/2015/05/reading-ashrae-table-information-from-elements.html
![image](https://user-images.githubusercontent.com/31106432/152714011-41097a33-91aa-4331-8483-f21d294614d3.png)

**Comment by jeremytammik** [comment]
@chuongmep  are you sure this functionality is appropriate for RevitLookup? It seems rather highly MEP specialised for me, whereas RevitLookup (so far) is a completely generic Revit database lookup tool. Still if you think it is appropriate, would you like to submit a pull request for the functionality you suggest?

**Comment by chuongmep** [comment]
@jeremytammik  Currently, I don't have any pull requests at the moment, but I'll consider seeing if they're suitable for inclusion before I do.

**Comment by Nice3point** [comment]
@chuongmep 
![изображение](https://user-images.githubusercontent.com/20504884/218325191-de6df98f-1d68-4a31-995f-5d8cf971a91b.png)
I added support for services, we need to add more extensions for it

**Comment by chuongmep** [comment]
That readlly a good new with, thank you @Nice3point

**Comment by Nice3point** [comment]
@chuongmep 
![изображение](https://user-images.githubusercontent.com/20504884/218557761-fb4c13ff-2afc-4101-a3ac-425d97574538.png)
![изображение](https://user-images.githubusercontent.com/20504884/218557813-6fd30999-9498-4904-96df-75fe9b2f689d.png)
![изображение](https://user-images.githubusercontent.com/20504884/218557867-5a47737c-486d-44e9-ad4a-656e8f157da7.png)
![изображение](https://user-images.githubusercontent.com/20504884/218558010-bebe0fcb-f561-43fe-9c5e-3c9357cd7dbd.png)

**Comment by Nice3point** [comment]
Done
