### ISSUE TITLE
Null Reference Exception on GetNonControlledTemplateParameterIds

### ISSUE THREAD

**Issue by kraftwerk15** [jeremytammik/RevitLookup#132]
![image](https://user-images.githubusercontent.com/30668448/154701586-df9640a9-e2b9-497a-b917-f0ec863ffcdb.png)

Clicking on GetNonControlledTemplateParametersIds in the UI throws this error:

![image](https://user-images.githubusercontent.com/30668448/154701752-eb1c0ab8-4e5d-4dac-97bf-e5700025048c.png)

Which after continuing in the debugger, immediately crashes Revit. :)

**Comment by kraftwerk15** [comment]
This may be in relation to issue #35

**Comment by jeremytammik** [comment]
Immediately crashing Revit is bad. The API should never be able to do that. A minimal reproducible case for that would be handy to submit to the development team. I suppose a minimal BIM and detailed step-by-step instructions to reproduce using RevitLookup would be sufficient. However, I see no connection with #35... what connection do you see?

**Comment by kraftwerk15** [comment]
I just briefly looked at #35 with the comment in there on some things may not be working. Which is how I thought this was related.

To be able to recreate this, you could open the rac_basic_sample_project.rvt, in RevitLookup > SnoopDB, scroll down to ViewPlan, click on anyone of the view plans, then scroll down and select GetTemplateParameterIds. It will display an UnhandledException dialog. Here is my output:

[https://pastebin.com/SnM4wzng](https://pastebin.com/SnM4wzng)

Whenever I was debugging, it would crash Revit and the debugging session. Whenever I was not debugging, it would display the UnhandledException window and allow me to close the Exception and continue with Revit. It may be how I've set up my debugging session that crashes Revit.

**Comment by Nice3point** [comment]
@kraftwerk15 namespace ```RevitLookup.Snoop.Data.SnoopableObjectWrapper``` does not exist, do you have an outdated fork? I don't get this error

If you check this box, uncheck it. Debugger can kill the process when such an error occurs
![изображение](https://user-images.githubusercontent.com/20504884/154838947-60c63b83-cd9b-4524-97e3-5a035abb7ee9.png)
