### ISSUE TITLE
Improve way see duplicate parameters ! 

### ISSUE THREAD

**Issue by chuongmep** [jeremytammik/RevitLookup#140]
Dear @jeremytammik and @Nice3point 
I thinked about this, whether we have any way to improve that when see some duplicate  parameter like this ? 
Should we make a small improvement so that users can quickly tell the exact difference between them?
![image](https://user-images.githubusercontent.com/31106432/174250346-a557c35a-a01b-4f52-8831-19f2b3cb78b3.png)

Kind Regard !

**Comment by jeremytammik** [comment]
interesting thought, indeed. definitely a useful suggestion. what would be the minimal identification and differentiation criteria? would it be possible to determine and display them up front for each parameter, directly in the left-hand column?

**Comment by chuongmep** [comment]
I think about add IsReadOnly like **Sheet Number(ReadOnly)** but may be it not enough.I think need more developer join and discuss more than about this.
![image](https://user-images.githubusercontent.com/31106432/174253396-8735eeb2-895f-427b-8c66-ff92049e3ba3.png)

**Comment by jeremytammik** [comment]
if you would like more input from other developers, i would raise the issue in the Revit API discussion forum and maybe even specifically ask the two super-users RPThomas108 and FAIR59 for their thoughts on it.

**Comment by chuongmep** [comment]
@jeremytammik nice thanks you ! I will wait respone before can do or not, because i still not ensure IsReadOnly will good for all case.

**Comment by Nice3point** [comment]
I don’t have any comments on this yet, personally I don’t feel uncomfortable with this behavior, I need the opinion of other users
