### ISSUE TITLE
MSI Installation Option: Per Machine Installation

### ISSUE THREAD

**Issue by peterson-m** [jeremytammik/RevitLookup#143]
Good Morning-

Recently at my organization there was a request by an end user to use the Revit Lookup add-in. During testing, we noticed that the default installation directory for the add-in is the active users roaming directory (C:\Users\%username%\AppData\Roaming\Addins\Revit\Addins\%YEAR%\RevitLookUp/Revitlookup.dll) at the time of installation.

From an application management perspective, this makes it challenging to streamline upgrades/add-in removals as the active user at the time of installation needs to be logged into the workstation and the fact that the add-in doesn't install across user accounts on the workstation. 

As a result of the installation directory changing, the LOCAL SYSTEM account (used by many centrally managed application solutions) can no longer handle the installation/uninstallation of the add-in without the end user being logged into the machine. In the past, the add-in installed in the Program Data directory (C:\ProgramData\Autodesk\Revit\Addins\2019\RevitLookup.dll) which appears to have allowed for 'Machine-wide installation'.

We would like to have the option to deploy the add-in to all Revit users in the future. However, without a machine-wide installation option are hesitant to do so. As a suggestion, you may want to give end users the option to install the MSI a machine-wide context as well as the current per-user context.

**Comment by Nice3point** [comment]
Ok, no problem, we will release the next releases for the machine and for each user

**Comment by Nice3point** [comment]
Build for the user is good because it does not require administrator rights to install

**Comment by peterson-m** [comment]
That makes sense regarding per user installation. It's nice to have both options.

Thank you for the quick response.

**Comment by Nice3point** [comment]
@peterson-m https://github.com/jeremytammik/RevitLookup/releases/tag/2023.1.0
portable - for each user
another - for each machine

**Comment by peterson-m** [comment]
Thank you, Jeremy. I really appreciate having both options for the installation.

**Comment by jeremytammik** [comment]
The thanks are all due to Roman, @Nice3point ! Thank you, Roman!
