### ISSUE TITLE
RevitLookupArchive Missing method in Revit 2022

### ISSUE THREAD

**Issue by punderscoresmithuk** [jeremytammik/RevitLookup#144]
Hi Revitlookup team,

We recently tried installing RevitLookup v2023.1.0 on our systems. The install went fine and works as expected in Revit 2023. Happy days.

What we did notice though is that where the latest install installs RevitLookupArchive for Revit 2022 when we open that (Revit 2022.1.3) we get the below message about a missing method from the Nice3point.Revit.Extensions.dll assembly. I did a quick side by side object browser comparison between the versions deployed in the 2022 and 2023 addins folder (v2022.1.7 & 2023.1.7 respectively) and it looks at face value like they have the same methods 

![image](https://user-images.githubusercontent.com/51383696/213343730-8a4b6628-e225-486a-828f-7bb9899dc243.png)

It's not a biggie. Once I skip through that message RevitLookup seems to work fine. I'm more just curious to know if this is a problem being experienced by any others? 

Cheers, Pete

**Comment by Nice3point** [comment]
Most likely you have a different plugin installed with a different version of the library, Revit loads the very first one in alphabetical order. You can change the version of the library for other plugins, or you can update the version in Lookup itself to a newer version within the same Revit version. And expect the next major update, work is actively underway

**Comment by punderscoresmithuk** [comment]
Thanks for the response mate.

I have tried removing all of my plugins and when the .addins for RevitLookup and RevitLookupArchive are both present I get the error but I can load both of them individually. Just not together. Even with all other plugins removed.

**Comment by jeremytammik** [comment]
i suggest that you remove RevitLookupArchive as well. what is it, anyway? do you really need it at all?

**Comment by Nice3point** [comment]
I don't know what you're doing in this situation, but delete RevitLookupArchive and wait for the spring update

**Comment by punderscoresmithuk** [comment]
@jeremytammik unsure what it does to be honest. It ships as part of the Lookup installer

@Nice3point Apologies. What I meant was I had removed for addin manifest for every other plugin to stop from loading.

Will remove RevitLookupArchive and wait for the next update.

Thanks for the responses
