### ISSUE TITLE
RevitLookup 2017 Missing Post Build Event

### ISSUE THREAD

**Issue by arif-hanif** [jeremytammik/RevitLookup#15]
@jeremytammik in the past the addin had a post build event which is not there in the current release for 2017. It does not need to be there but was nice have.

**Comment by jeremytammik** [comment]
what did it do? can you point to the diff where it disappeared? it is probably totally trivial to add it again. do you want to do so and submit a pull request?

**Comment by arif-hanif** [comment]
Did a PR, it was to copy the addin manifest and dll to the addins folder

**Comment by jeremytammik** [comment]
thank you, perfect! merged and published as release 2017.0.0.6: https://github.com/jeremytammik/RevitLookup/releases/tag/2017.0.0.6
