### ISSUE TITLE
Snoop section Command missing.

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#150]
First of all congratulations! The new version/UI looks amazing. 

I was testing in Revit 2024 and found some annoying problems.

The SnoopSelectionCommand does not exist. Only on the modify panel which means is not possible to create a shortcut because the command was not registered in the normal way. 

The best approach should be to register the SnoopSelectionCommand in the main RevitLookup panel and create the Modify as well, you could create a copy of the RibbonItem or create a new one like the current code.

Another thing that would be great is a way to disable the Modify in the configuration of the plugin, make the RibbonPanel visible/not visible should make the trick.

I gonna take a look at the project and create a PR if manage to fix that.

**Comment by Nice3point** [comment]
I haven't run Revit 2024 unfortunately, so I can't look and tell how it looks. However, it compiled without any problems. Has Autodesk changed the code of the AdWindow library ?

Yes, thanks if you take a look and find the cause of this malfunction.

About duplicating the SnoopSelection command and disabling it on the ribbon, other people's opinions need to be gathered as well

**Comment by ricaun** [comment]
You cannot find the Snoop Selection in the Keybord Shortcut if you add the Panel/Button in the modify tab using AdWindow.
The SnoopSelectionCommand was never registered in Revit.
I created my own version so I can find the command and add a shortcut
![image](https://user-images.githubusercontent.com/12437519/229845945-6ae5b10d-f604-43e2-a00d-a17a3ff5b775.png)

**Comment by Nice3point** [comment]
Sorry, I misunderstood the problem. Shortcut support will be available in the next update

![изображение](https://user-images.githubusercontent.com/20504884/229853427-efd95811-a663-41f1-89a6-ab934ee79b69.png)

About the button on the "Modify" tab - not all users have yet appreciated the new version and more feedback is needed

**Comment by ricaun** [comment]
I personally hate when a plugin adds stuff in the modify tab without my consent, a shortcut always works fine for years.

**Comment by Nice3point** [comment]
Others say it's one of the best solutions, so it's a matter of taste. Hotkeys are used by maybe 10% of users, if not less

**Comment by andydandy74** [comment]
Hi, I'm one of the 10% hotkey users ;-) 
Although I really like the idea of having the snoop selection tool available in the Modify tab I would miss being able to bring up the command via hotkey, Can't we have both?

**Comment by Nice3point** [comment]
> Hi, I'm one of the 10% hotkey users ;-) Although I really like the idea of having the snoop selection tool available in the Modify tab I would miss being able to bring up the command via hotkey, Can't we have both?

Hotkey support will, in future updates. For now, let's discuss the position of the button itself https://github.com/jeremytammik/RevitLookup/discussions/151

**Comment by ricaun** [comment]
Neat! 

Oh my, why did you remove the panel and adding again... Just to sneak the command to the modify tab. 

I am pretty sure the keyboard shortcut is not gonna update, which means if the user opens Revit and adds a shortcut in the selection command and now remove/add the selection command to the modify tab.

Now you are using 'RibbonItemDictionary' to remove the panel from Revit internal dictionary. Revit was not designed to remove ribbons in the run time.

I don't know if the RevitLookup is the best place to mess around with not public Revit API.

**Comment by Nice3point** [comment]
@ricaun shortcuts work without problems, your version did not support hotkeys. An additional fix will be added once UIFrameworkServices is published in Nuget. Also, this is only done when switching the ribbon after starting the plugin, normally no one would do this. During normal loading, everything is executed in the usual way and does not save data to static variables. If you know a better way to make it work without static variables, let me know

**Comment by Nice3point** [comment]
> Revit was not designed to remove ribbons in the run time.

Its internal code allows this, it is only hidden to the public Api

**Comment by Nice3point** [comment]
And please let's discuss problems and solutions and offer alternatives, if any, instead of empty criticism. Thanks

**Comment by ricaun** [comment]
Not using static variables, that's a requirement I didn't know.

I just point the things that gonna fail and already point a solution, we never know what the user gonna do in the other end.

I didn't have time to test before the release, I didn't think that gonna change all the UI and others, was really surprised 😯

When I first test the button was in the modify tab and I can sign a shortcut...

I gain a button that haunt my modify tab and lose a feature the I use, really annoying.

Now look like is working, but how know what happens when you mess with non public Revit Api there is a reason that is no public. I personally avoid to use.

Let's create a PR.
