### ISSUE TITLE
Fatal Error, Unrecoverable Error

### ISSUE THREAD

**Issue by GerhardPaw** [jeremytammik/RevitLookup#153]
Hello,

I installed the lastest release for Revit 2022 from yesterday.
Revit crashes as soon as i want to use Revit Lookup because of Fatal Errors or Unrecoverable errors.

![image](https://user-images.githubusercontent.com/97836426/230310190-24c14182-927b-4e4d-b03d-38144a5eaea0.png)

**Comment by GerhardPaw** [comment]
Hello @GerhardPaw 

I work on Windows 10 Enterprise, 64 Bit. I have installed PyrEvit and DiRootsOne installed.
Yes i have the mentioned file in sys32!

**Comment by Nice3point** [comment]
Strangely, the error is related to the absence of this library. We will explore this problem further and see the situation with other users, temporarily you can use the previous version of RevitLookup https://github.com/jeremytammik/RevitLookup/releases/tag/2023.1.0

**Comment by Nice3point** [comment]
Related issues:
https://github.com/lepoco/wpfui/issues/481
https://github.com/lepoco/wpfui/issues/275

**Comment by GerhardPaw** [comment]
Thanks for your help! Let me know if i can help by sending any file :)

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/discussions/149#discussioncomment-5571217

**Comment by Nice3point** [comment]
Fixed in 2024.0.2
