### ISSUE TITLE
Snoop string in List of strings in extensible storage in old RevitLookup shows list of characters

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#156]
Прывітанне, Раман, ці чаканыя такія паводзіны старога RevitLookup? Як вы думаеце, ці ўбачыць карыстальнік чаканы радковы аб'ект, калі ён пераключыцца на RevitLookup 2024? https://forums.autodesk.com/t5/revit-api-forum/snoop-db-snoop-selection-with-an-array-of-strings/td-p/11884127 -- Дзякуй! Джэрэмі

**Comment by Nice3point** [comment]
Hi Jeremy, it's very nice that you use my native language ☺️ In the new version, data type support is more advanced and there is no such problem anymore

**Comment by jeremytammik** [comment]
My pleasure entirely. My first attempt ever. Thanks to g00g13 xlate. Thank you very much for answering Ivo directly! Hope you had a wonderful Easter! I'll get going on the What's New in the Revit 2024 API blog post now... Cheers, Jeremy

**Comment by rui-tang-symetri-com** [comment]
Hi @jeremytammik , unfortunately this is still an issue.

![2024-11-04 18 20 29](https://github.com/user-attachments/assets/a74a5622-45d4-4403-98f5-9a726500dc87)

This is RevitLookup 2022.03.10
![2024-11-04 18 22 35](https://github.com/user-attachments/assets/38812b30-092e-4bd8-b11a-6790fc1719f9)
