### ISSUE TITLE
repetitive icons for each menu entry

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#158]
Do the repetitive icons for each menu entry really help? I think they look distracting, consume unnecessary space, and would better be removed:

<img width="853" alt="revitlookup2024" src="https://user-images.githubusercontent.com/4264589/234624449-52f5b783-2920-4c0d-888f-89358e4c229d.png">

The main icon in the ribbon looks fine, but i suggest the others either be replaced by small individual icons or simply be removed, so that the men u text entries can speak for themselves. What do you think?

**Comment by Nice3point** [comment]
Yes we have been talking to @chuongmep about this and are thinking of redesigning the ribbon. Before, when there weren't many options it wasn't a problem, but now that there are a lot of them, yes, the list does get long.  We need to discuss with everyone what style of ribbon we should make and what set of buttons

Of the possible options, we came up with this case. With grouping
![изображение](https://user-images.githubusercontent.com/20504884/234636521-7d789a37-370f-44ea-b6f2-ca8ec7511040.png)

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/discussions/159
