### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#161]

**Comment by jeremytammik** [comment]
I deleted release 2024.0.3. I hope that does not break anything. I'll update the blog post now to remove the notes from that.

**Comment by jeremytammik** [comment]
Can you make a new release 2024.0.4 with the other changes but without the debug tab, please? Thank you!

**Comment by NeVeSpl** [comment]
But that did not happen in 2024.0.3, all releases 2024.0.x are exposing Debug tab ....

**Comment by jmcouffin** [comment]
A whole new world opened up ;p

**Comment by jeremytammik** [comment]
oh. well, sorry. the powers that be are not happy. they noticed it now due to the blog post. i removed the announcement and deleted the 2024.0.3 release. very sorry about that. anyway, you can check out how it is done for yourself now you know that it exists...

**Comment by jeremytammik** [comment]
Here is the official statement I received (along with a lot of other comments):

3 days ago, changes made by (who I assume to be) a third party with username Nice3Point to RevitLookup have enabled the Revit Debug tab and built the UI around it.  The features and capabilities in there are not for public use and could actively cause problems for users and for Autodesk if used.  We need to revert changes in Revit Lookup ASAP: 
https://github.com/jeremytammik/RevitLookup/commit/8f30383e516934f0480d1b5e439fcad69d70f429
 
I did not see any indication that any of the third party contributions made are being reviewed by Jeremy or others at Autodesk.  I'm concerned about other code in this "sample app" referencing UIFramework and UIFrameworkServices internal .NET assemblies (and yes, I remember that the blog post contents sometimes skirted the line to highlight things that could be done with these).  This blows past the line we'd like to have in any Autodesk-associated Revit tool and must be reverted ASAP.

**Comment by jeremytammik** [comment]
Thank you for the super quick action!

**Comment by Nice3point** [comment]
It is very sad to hear such a position from Autodesk. After all, we are not damaging the company's image in any way and are not interfering with sales of software products. We just give more opportunities to developers. It would be nice if the company improved its product as actively as we improve RevitLookup instead of imposing new limitations

**Comment by jeremytammik** [comment]
No comment :-)

**Comment by jmcouffin** [comment]
My 2Cents Comment :-) @jeremytammik:

I am with you on that @Nice3point 
At least now I know how to activate it ;p

> It is very sad to hear such a position from Autodesk. After all, we are not damaging the company's image in any way and are not interfering with sales of software products. We just give more opportunities to developers. It would be nice if the company improved its product as actively as we improve RevitLookup instead of imposing new limitations


<details>
  <summary>For python lovers:</summary>

```python
import clr
clr.AddReference("UIFramework")
from UIFramework import *
# Add debug tab to ribbon
RevitRibbonControl.RibbonControl.Tabs.Add(RevitRibbonControl.RibbonControl.DebugTab)
# Remove panel to debug tab
RevitRibbonControl.RibbonControl.Tabs.Remove(RevitRibbonControl.RibbonControl.DebugTab)
```

</details>
