### ISSUE TITLE
Already not showing BuiltInCategory

### ISSUE THREAD

**Issue by dronovdmitry** [jeremytammik/RevitLookup#162]
version 2021.2.4 - already not show BuiltInCategory
![image](https://user-images.githubusercontent.com/132697635/236522992-9cbabe04-3ee3-46f0-9794-9c74f85a484f.png)

**Comment by dronovdmitry** [comment]
I found one of the old version of RevitLookup for 2021 revit and BIC is located here
![image](https://user-images.githubusercontent.com/132697635/236524382-bc96623c-5b5f-4d91-bd34-ce88e2f3a8bc.png)

**Comment by Nice3point** [comment]
В старой версии это свойство добавлено вручную, его не существует в API. Не знаю на сколько хорошая идея стоит ли его добавлять снова для версий 21-22.  В Качестве альтернативы на данный момент вы можете воспользоваться этим разделом с поиском по имени 

In the old version this property was added manually, it does not exist in the API. I don't know if it's a good idea to add it for versions 21-22.  As an alternative at the moment you can use this section 

![изображение](https://user-images.githubusercontent.com/20504884/236526723-1c8b9e82-33f8-4d5c-b3e4-7039167f9292.png)

![изображение](https://user-images.githubusercontent.com/20504884/236526843-7d9bf4e7-b808-474e-a730-a8335518d48d.png)

**Comment by Nice3point** [comment]
Released 2024.0.7
