### ISSUE TITLE
GetMaterialIds is not clickable

### ISSUE THREAD

**Issue by denizmaral** [jeremytammik/RevitLookup#163]
I wanted to see material of a DirectShape and it did not let me to open that:

![grafik](https://github.com/jeremytammik/RevitLookup/assets/55183821/b4574caa-06b6-47ec-8ea7-5112773911f2)

**Comment by Nice3point** [comment]
Thanks for the report, the problem is known and already solved. Wait for the next update, there was a typo in the code

https://github.com/jeremytammik/RevitLookup/commit/f371559f1cb74204fa89a1a42159d35689de2d8f

**Comment by denizmaral** [comment]
Thank you very much!
