### ISSUE TITLE
UI/UX: close all buton?

### ISSUE THREAD

**Issue by CADBIMDeveloper** [jeremytammik/RevitLookup#172]
Would be nice to have an ability to close all Revit lookup windows

**Comment by ricaun** [comment]
if the `Escape` key makes the active RevitLookup window close and the owner is activated, you could press `Escape` `Escape` `Escape` and everything gonna close.

**Comment by CADBIMDeveloper** [comment]
@ricaun , it doesn't work on my machine (Win 10) for some reason.

**Comment by CADBIMDeveloper** [comment]
@ricaun , good point, but having extra button is also a good thing IMO

**Comment by Nice3point** [comment]
Escape button will definitely be added, a separate button to close all instances is not sure

**Comment by Nice3point** [comment]
I added closing a window on Esc, what combination would you like for closing all windows?
1. Shift + Esc
1. Ctrl + Shift + Q
1. Alt + Shift + F4
1. Ctrl + Shift + W
1. Alt + Shift + X
1. Ctrl + Alt + C
1. Ctrl + Alt + X
1. Alt + Shift + Z
1. Ctrl + Shift + S


Or do you have any other suggestions?

**Comment by ricaun** [comment]
`Shift + Esc` makes sense to me

**Comment by CADBIMDeveloper** [comment]
`Ctrl + Alt + X` as an option

**Comment by jeremytammik** [comment]
On a Mac, Command-Q quite a program. The program in this case would be Revit.exe. To quit a subprocess, some modified on top of Command-Q would make sense. It is certainly possible to define several different key, but is that desirable? Easy of finding them versus danger of confusion?

**Comment by Nice3point** [comment]
All have different ideas 🙈
I think if doing window closing on ESC then closing all windows should also be with ESC and usually add a shifft. If we want to close one window with ctrl+Q, it makes sense to close all windows with ctrl+shift+Q

**Comment by Nice3point** [comment]
The dev branch currently has the shift + esc combination available to close all windows and esc to close one window. We can change this at any time when we come to a consensus

**Comment by ricaun** [comment]
> The dev branch currently has the shift + esc combination available to close all windows and esc to close one window. We can change this at any time when we come to a consensus

Usually inside Revit `Esc` closes the UI open or cancels the command in the UI.

One thing that could be handy and kinda make close all useless
is, if you `Espace` and close a RevitLookup the other RevitLookup opened window is Activate, and you could `Espace` to close the first one, then press `Espace` to close the next, then press `Espace` to close the next, and so on.

At least make sense to activate the windows father.
