### ISSUE TITLE
Add to Revit Lookup to Modify Tab

### ISSUE THREAD

**Issue by BenBarfootWSP** [jeremytammik/RevitLookup#177]
Hi,

I don't know if anyone has mentioned it yet but when you add the button to the Modify Tab (shown in Image 1) it changes the ribbon type from a "modelling" ribbon (shown in Image 2) to "edit family" ribbon (shown in Image 3). I am guessing this is a bug.

Image 1
![image](https://github.com/jeremytammik/RevitLookup/assets/116065756/39207694-5dd7-4f7b-afa7-9df5f5d32e4c)

Image 2
![image](https://github.com/jeremytammik/RevitLookup/assets/116065756/5e476b1e-2233-4e6e-9479-062f1e85c9d5)

Image 3
![image](https://github.com/jeremytammik/RevitLookup/assets/116065756/31a0e1db-6344-499a-879b-83e36f1785fa)

Ben

**Comment by Nice3point** [comment]
Fixed in the next update
