### ISSUE TITLE
Extensible Storage Schema field values

### ISSUE THREAD

**Issue by russgreen** [jeremytammik/RevitLookup#184]
I can't seem to see the field values for the storage entity.  I get only get as far as seeing the list of fields..  In the Winforms version, you can see the values being stored as well.  Apologies if I'm looking in the wrong place but this would be a useful additional feature.

**Comment by NeVeSpl** [comment]
You can always use an [alternative tool that offers access to Extensible Storage Scheme](https://github.com/NeVeSpl/RevitDBExplorer#better-support-for-revit-extensible-storage). (:

**Comment by russgreen** [comment]
The above seems OK if there is only one field. 

I have a scheme that I cannot click on Get(string)
![Screenshot 2023-09-07 075212](https://github.com/jeremytammik/RevitLookup/assets/1886088/1a74a5c5-6461-43d1-8ad0-22b838a6ea51)

But I can click into the scheme and then get the list of fields.  I just can't see the values of those fields unless I use the Winforms version of RevitLookup or RDBE.

**Comment by Nice3point** [comment]
@russgreen can you share any project (.rvt) with this schema ?

**Comment by Nice3point** [comment]
@russgreen Can you send file again? Link is no longer valid

**Comment by russgreen** [comment]
[rac_basic_sample_project_schemademo.zip](https://github.com/jeremytammik/RevitLookup/files/13402693/rac_basic_sample_project_schemademo.zip)

Revit  2022 sample attached.

**Comment by Nice3point** [comment]
@russgreen 
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/6237b103-a4f1-45c2-b439-dd042870d89a)
Fixed
