### ISSUE TITLE
Error when using Revit Lookup in  Revit 2023

### ISSUE THREAD

**Issue by LoRue656Plus10** [jeremytammik/RevitLookup#185]
I am getting an error when trying to use Lookup.  I do not have Revit 2024, but my understanding is that the newest Lookup will work with all versions?  If that is not the case, then it was not clear.  
The error is:  
'Could not load type: 'Autodesk.Revit.DB.EvaluatedParameter' from assembly 'RevitAPI', version=23.0.0.0, Culture=neutral, PublicKeyToken=null'.   
So, it is looking for the Revit 2024 method which does not exist in 2023.  Does this mean we should not be using Lookup v24?  In the documentation, it clearly shows Revit 2023.1 being used. 
Also, when the addin was installed, it defaulted to the appdata addin folder '2024'.  I ended up copying the files to my 2023 folder and it loaded.  It was previously ignored even though it said the install was successful.

![RevitLookup2024Error](https://github.com/jeremytammik/RevitLookup/assets/68364429/d5dfd344-783e-4671-b760-10af642491e9)

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/issues/160

**Comment by LoRue656Plus10** [comment]
Oh dang!  Sorry about that.  Thanks for getting back to me.
