### ISSUE TITLE
Wrong DataContext in Dashboard  page

### ISSUE THREAD

**Issue by IlyaNavodkin** [jeremytammik/RevitLookup#201]
**Description**:
Are you sure that DataContext (Dashboard page)  should be assigned to View? Maybe there should be a **_DashboardViewModel_** here?

**Where**:
https://github.com/jeremytammik/RevitLookup/blob/3b0a49e02247ce24b8837b83c019740e936e7d18/source/RevitLookup/Views/Pages/DashboardView.xaml#L10

**Comment by Nice3point** [comment]
Sure, DashboardView must implement the INavigableView<ViewModel> interface
