### ISSUE TITLE
Copy Value popup command crashes Revit 

### ISSUE THREAD

**Issue by ricardyn** [jeremytammik/RevitLookup#202]
When I try to use Copy Value command on popup window Revit crashes every time.

![image](https://github.com/jeremytammik/RevitLookup/assets/14896455/52341c0b-b4e9-4533-b949-84529e7e1378)

Error stack
![image](https://github.com/jeremytammik/RevitLookup/assets/14896455/62371e37-0842-4a53-9faf-55106134f84f)

**Comment by Nice3point** [comment]
@ricardyn try 2024.0.13
