### ISSUE TITLE
Revit 2025 - Allow Multiple Selection

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#226]
When `Snoop Face`, `Snoop Edge`, `Snoop Point` and `Snoop Linked` the `Allow Multiple Selection` ribbon panel appear.

![RevitLookup - Allow Multiple Selection - 2024-04-30 14-58-17](https://github.com/jeremytammik/RevitLookup/assets/12437519/fffc64d3-16c9-4651-be43-f90432064176)

That's a Revit 2025 UI issue, here is a forum reference: https://forums.autodesk.com/t5/revit-api-forum/weird-allow-multiple-selection-revit-api-2025/td-p/12731348

**Comment by Nice3point** [comment]
Hi Luiz. This issue is related to the Revit API, not RevitLookup. This is also where PickObject is used:
https://github.com/jeremytammik/RevitLookup/blob/47a4cb64e469b1e937345417d5d139b1b04f4ead/source/RevitLookup/Core/Selector.cs#L175

Waiting for fixes from the Revit team

**Comment by Nice3point** [comment]
Fixed in 2025.2.0 https://help.autodesk.com/view/RVT/2025/ENU/?guid=RevitReleaseNotes_2025updates_2025_2_Resolved_Issues_2025_2_html
