### ISSUE TITLE
Revit freezes during Document.Export() with RevitLookUp Event Monitor running

### ISSUE THREAD

**Issue by Rpixel111** [jeremytammik/RevitLookup#234]
I've encountered an issue where executing
`Document.Export(string folder, IList<ElementId> viewIds, PDFExportOptions options)`
while the running the Event Monitor in RevitLookup leads to Revit freezing. I've tried various configurations of the PDF Export options, but the freeze persists.

When the Event Monitor is not running, calling Document.Export works without any issues.
It seems like there's something incompatible happening within those processes.

Thank you.

**Comment by Nice3point** [comment]
PDF export with Event Monitor works fine with only single sheet
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/e4ac1a25-7c3d-4c88-a745-0fb36376c9e7)

But stuck with multiple sheets
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/6c1063ad-edce-41a8-9727-72fbbdf0521e)

**Comment by Nice3point** [comment]
@Rpixel111 please provide information how long it takes to export without Event Monitor, and with it. In seconds\minutes. nothing should collide in the code, except for frequent triggering of FailuresProcessing event
