### ISSUE TITLE
Slow responsiveness when Debugger is attached

### ISSUE THREAD

**Issue by guffab** [jeremytammik/RevitLookup#237]
Hi,

I found "RevitLookup" to be a very handy tool for developing my own Revit plugin and I use it daily.

Although it is usually **very** responsive, it takes considerably longer per click (5-10 seconds) when I open Revit with the VS Debugger attached.

Any idea why that might happen?

**Comment by Nice3point** [comment]
@guffab during debug uses unoptimised code, any Debug build will be slower than Release. However 5-10 seconds is not normal, without more information there is no idea what the problem is

**Comment by guffab** [comment]
@Nice3point I think there is also a misunderstanding. I am not debugging the RevitLookup tool, but my own plugin. As far as I know, this should not have any affect on Revit or other plugins.

**Comment by NeVeSpl** [comment]
Plugins are running inside Revit process, debugger can be attached only to the whole process, therefore you are debugging every loaded assembly that is not build with optimization enabled or there are available debug symbols (*.pdb) for it.

**Comment by guffab** [comment]
So am I correct to assume the version of RevitLookup I installed was not built in Release Mode and it also includes .pdb files?
Could this be the reason for the issue I am seeing?

**Comment by Nice3point** [comment]
RevitLookup is published in Release mode, and does not ship with pdb files. 
If your plugin is not protected by NDA, you can send us the source code to understand what the problem is. We cannot answer your question without analysing it

**Comment by guffab** [comment]
Here is a bare-bones version of my plugin. To reproduce the issue:

1. Unpack
2. Open in Visual Studio
3. Start with Debugger
4. Open existing project or create a new one
5. Select an element and click RevitLookup > Snoop Selection

[ExamplePlugin.zip](https://github.com/jeremytammik/RevitLookup/files/15332182/ExamplePlugin.zip)

**Comment by Nice3point** [comment]
@guffab the code is completely empty, it doesn't cause any problems, everything works fine as before during debugging
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/0d88f4d6-8c1c-4e66-837d-283d4c72c51d)

**Comment by guffab** [comment]
Intertestingly enough, on my PC (and those of my colleagues) there doesn't have to be any actual code in the project to reproduce it. Did you test it with the Visual Studio Debugger or only with Jetbrains Rider?

**Comment by guffab** [comment]
I just checked on another colleagues PC. He did not have this problem, but he also had an older version installed:
![image](https://github.com/jeremytammik/RevitLookup/assets/106798951/494e2c91-f6d8-4410-88b5-6aa0b272c43f)

After he updated, he had the same problem. <br><br>
<hr>

Here are two videos showing the difference (with and without Debugger):

https://github.com/jeremytammik/RevitLookup/assets/106798951/1a0d5323-1598-4221-8b94-46099f282cea


https://github.com/jeremytammik/RevitLookup/assets/106798951/844ce9d8-c9bd-4ba6-babc-af97d9447ef2

**Comment by Nice3point** [comment]
@guffab i see. indeed the slowdown in performance is felt quite critically. 

Maybe Visual Studio users can help you, I use Jet Brains debugger and I can't test VS debugger
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/b20a1b75-d754-4585-b445-3ad58a481d1b)

**Comment by ricaun** [comment]
I tested in Visual Studio 2022 with the last version (2024.1.4) and looks normal. I'm using Revit 2024.0.

Only the **EventMonitor** that is showing something in the console:
```
2024-05-17 14:00:14 [DBG] RevitLookup.Core.EventMonitor: RevitLookup EventMonitor: Autodesk.Revit.DB.Document.DocumentClosing
2024-05-17 14:00:14 [DBG] RevitLookup.Core.EventMonitor:  - success
...
```
