### ISSUE TITLE
Suggesting Icon

### ISSUE THREAD

**Issue by eirannejad** [jeremytammik/RevitLookup#24]
Not the best but I love to see an icon on the Revit Lookup button. Maybe:
![rlookup-96](https://cloud.githubusercontent.com/assets/8197916/22996996/97994410-f385-11e6-872a-c0cec237a0bb.png)

[RLicon.zip](https://github.com/jeremytammik/RevitLookup/files/778487/RLicon.zip)

**Comment by jeremytammik** [comment]
sure, looks great! would you like to submit a pull request with code to set it up and display it? thank you!

**Comment by eirannejad** [comment]
With pleasure. I'll send one soon

**Comment by jeremytammik** [comment]
how soon?  :-)

**Comment by eirannejad** [comment]
Done! Sorry for the delay :+1:
