### ISSUE TITLE
`main.yml` file in the release folder?

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#243]
I was looking the last release project and noticed that in the `publish` folder there is a `main.yml` file.

Looks like the `Serilog.Sinks.Autodesk.Revit` is adding the `main.yml` file in the content for some reason.

* https://github.com/dosymep/Serilog.Sinks.Autodesk.Revit

The odd part is that is only added in the `publish` folder, the `Debug R25` does not have the file, maybe the copy is coping extra content.

This is coping all the content that is not Never, if the file is set as  `Content` the file is copy to the `publish`. Don't know if is intended feature.
```xml
<FilteredContent Include="@(Content)" PublishDirectory="%(Content.PublishDirectory)" Condition="'%(Content.CopyToPublishDirectory)' != 'Never'"/>
```
https://github.com/Nice3point/Revit.Build.Tasks/blob/d778daf98e933441b7931a4ab2460aa91a066f5a/source/Nice3point.Revit.Build.Tasks/targets/Nice3point.Revit.Publish.targets#L22

If I set any file as `Content` is copy to the `publish` folder, even with the `Copy to Output Directory` to `Do not copy`.

**Comment by Nice3point** [comment]
I guess the problem is related to this line:
https://github.com/dosymep/Serilog.Sinks.Autodesk.Revit/blob/master/src/Serilog.Sinks.Autodesk.Revit/Serilog.Sinks.Autodesk.Revit.csproj#L75C7-L75C90

and it's included in the Nuget package
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/565dbe4c-d95c-4256-9103-cb88c41d7111)

**Comment by Nice3point** [comment]
> This is coping all the content that is not Never, if the file is set as `Content` the file is copy to the `publish`. Don't know if is intended feature.

Yeah, this is expected behaviour
https://github.com/Nice3point/Revit.Build.Tasks/tree/d778daf98e933441b7931a4ab2460aa91a066f5a#publishing

**Comment by ricaun** [comment]
Yes, but I'm not explicit setting the `CopyToPublishDirectory` to never.

![image](https://github.com/jeremytammik/RevitLookup/assets/12437519/ad2ce62a-b4e6-450a-a175-54541638287e)
![image](https://github.com/jeremytammik/RevitLookup/assets/12437519/371403ae-a35b-488c-8ff0-ac8b1c86e80e)
![image](https://github.com/jeremytammik/RevitLookup/assets/12437519/c00a3741-fc28-4305-946b-212968bf0cdc)

You probably need to check if `Content.CopyToPublishDirectory` is not empty or only copy is is `Always` or `PreserveNewest`.

**Comment by ricaun** [comment]
> But you show `CopyToOutputDirectory`) This is not the same as `CopyToPublishDirectory` this file is not included in the bin directory

Ops, didn't see that is two different properties.

So, by default gonna copy every content to the publish folder, even files that is not coping to the output folder.

**Comment by dosymep** [comment]
yep, I will remove main.yml :)

**Comment by ricaun** [comment]
> yep, I will remove `main.yml` :)

Yep! 

@Nice3point Still find odd that by default all the content is copy to the `publish` folder, I thought the `CopyToOutputDirectory` was the main propriety used to copy to the `publish` as well.

**Comment by Nice3point** [comment]
> yep, I will remove `main.yml` :)

you can write something like this:
`<None Update="$(SolutionDir)/.github/workflows/*.yml" Link="ci/%(Identity)" />`

Or just use SolutionItems to add this file to the Solution explorer

**Comment by Nice3point** [comment]
> @Nice3point Still find odd that by default all the content is copy to the `publish` folder, I thought the `CopyToOutputDirectory` was the main propriety used to copy to the `publish` as well.

Content implies the use of the file for publishing, its other purpose is wrong. And you should use None or something else, but not Content
https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#content

**Comment by Nice3point** [comment]
>I would definaly change to not copy.

Agree, I will update the publication to include PreserveNewest and Always

**Comment by ricaun** [comment]
> > I would definaly change to not copy.
> 
> Agree, I will update the publication to include PreserveNewest and Always

You could use the `PublishDirectory` as well to assume that the file need to be copy to the publish folder.

**Comment by Nice3point** [comment]
> You could use the `PublishDirectory` as well to assume that the file need to be copy to the publish folder.

It's more logical to split it up, and keep the 2 properties to be responsible for their own purpose

**Comment by Nice3point** [comment]
@ricaun new version is available 

In general, Microsoft's approach will now be used
https://github.com/dotnet/sdk/blob/f6a8556dab12a7c27d6d0e66e93194a42dcde25a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L422-L444

Always and PreserveNewest are handled separately as well
https://github.com/Nice3point/Revit.Build.Tasks/blob/main/source/Nice3point.Revit.Build.Tasks/targets/Nice3point.Revit.Publish.targets#L22-L23

RevitLookup I have updated, waiting for a fix in Serilog.Sinks.Autodesk.Revit

**Comment by dosymep** [comment]
done [Serilog.Sinks.Autodesk.Revit v2.0.1](https://github.com/dosymep/Serilog.Sinks.Autodesk.Revit/releases/tag/v2.0.1)
