### ISSUE TITLE
Add BuiltInCategory in element parameters

### ISSUE THREAD

**Issue by Kibatun** [jeremytammik/RevitLookup#249]
Hello, I tried to find BuiltInCategory parameter of an element in my Revit project, but couldn't find it in the latest version of Lookup.  Could you please bring it back as it was in previous versions (e.g. 2019.0012)? It would help a lot in writing plugins and understanding the code.
I'll show you how it was: 
var annotations = new FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_TitleBlocks).WherePasses(viewFilter).ToList();
 And as it is now:
var annotations = new FilteredElementCollector(doc).Where(elem => elem.Category.Id.ToInt64() == -2000280).WherePasses(viewFilter).ToList();

**Comment by Nice3point** [comment]
Duplicated https://github.com/jeremytammik/RevitLookup/issues/162 

Enable extensions, this is not a native API method method in versions before 2023

![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/6e5c03ee-e0c3-4c15-84d1-625dfd2f1820)

**Comment by Kibatun** [comment]
Thank you
