### ISSUE TITLE
Visualization setting dark theme have white background.

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#250]
The background in the dark mode is white in the Visualization setting 😐

Tested with the version 2024.1.5.

![image](https://github.com/jeremytammik/RevitLookup/assets/12437519/a55701c9-8f61-49dc-a561-2bb70fc7a99b)

**Comment by Nice3point** [comment]
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/a15018db-f763-4760-95a0-137d75bc45a1)
Fixed

**Comment by ricaun** [comment]
Neat! 

In the Solid there is not a way to scale the Solid shape only the cage, would be handy to have that option to scale the Faces as well.

![image](https://github.com/jeremytammik/RevitLookup/assets/12437519/2424f77b-6612-43fb-9a60-df1095d6491f)

**Comment by Nice3point** [comment]
@ricaun better to create a new issue with suggestion)

**Comment by ricaun** [comment]
> @ricaun better to create a new issue with suggestion)

Yes 😀
