### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by ninhpham96** [jeremytammik/RevitLookup#252]
![image](https://github.com/jeremytammik/RevitLookup/assets/116655628/59fc0cd8-ff87-4e56-b8b0-6ac55a10e618)
I just reinstalled the 2021 singler version, I encountered this error, how to fix it? Thanks.

**Comment by Nice3point** [comment]
You have another plugin installed with an outdated Extensions library that loads before RevitLookup. check your plugins and update them

**Comment by Nice3point** [comment]
Solved in https://github.com/jeremytammik/RevitLookup/releases/tag/2025.0.8
