### ISSUE TITLE
Structural Framing Visualize Geometry Not Updating

### ISSUE THREAD

**Issue by Keeps11** [jeremytammik/RevitLookup#253]
When a Structural Framing Element(Beam) has one of the Steel Connection(the in-build connection families, in the 'Steel' ribbon tab) used on it and then you modify the 'z Offset Value' parameter. The visualized geometry doesn't update as shown below. From what I can tell the Family Instance Transform isn't updating when the 'z Offset Value' parameter is changed. 
![image](https://github.com/jeremytammik/RevitLookup/assets/86806975/9dec1281-793a-4869-a620-a35aa47a515e)
![image](https://github.com/jeremytammik/RevitLookup/assets/86806975/5ca5b40e-8b3c-4bca-9287-243a42362da1)
![image](https://github.com/jeremytammik/RevitLookup/assets/86806975/4481ec89-7615-4167-b4f0-4b241b4b0e28)

**Comment by Nice3point** [comment]
Geometry in Revit is not binding to an element and is not updated when it is modified, so when updating an element, the get_Geometry() method must be called again to update the geometry

**Comment by jeremytammik** [comment]
maybe helpful do explicitly point this out in the wiki...

**Comment by Nice3point** [comment]
> maybe helpful do explicitly point this out in the wiki...

Maybe. I'll update this weekend, the thing is that Revit creates a new Solid when changing an element, instead of updating an existing one

**Comment by Keeps11** [comment]
Sorry for the late reply and some missing information. Even after I close Revit (or just lookup) and reopen and look at the same element without making any modifications this issue still remains. This issue doesn't happen for the element if a structural connection hasn't been added to it .

**Comment by Keeps11** [comment]
Sorry for late reply and some missing information. Even after restarting Revit or Lookup and looking at the same element without making any modifications the issue still remains. However through more investigation it seems that get_Geometry(Active View) returns what I would expect 
![image](https://github.com/jeremytammik/RevitLookup/assets/86806975/001fe820-e7fb-47c1-9464-e2c5444e021e)
but Model, medium/fine detail level returns this
![image](https://github.com/jeremytammik/RevitLookup/assets/86806975/4866d56e-b3cb-4f37-b82c-0eb7953ad968)
am I missing something, shouldn't these be the same
