### ISSUE TITLE
Request: Add WorksharingTooltipInfo Properties

### ISSUE THREAD

**Issue by ttiefenbach** [jeremytammik/RevitLookup#254]
I wondered if I could put in a request for a future release of the RevitLookup tool.  All out project have Worksharing enabled and I'm constantly being a detective to figure out "who done it."  It would be really helpful if RevtiLookup supported:

- WorksharingTooltipInfo.Owner
- WorksharingTooltipInfo.Creator
- WorksharingTooltipInfo.LastChangedBy
- WorksharingTooltipInfo.GetRequesters()

That way, I could see that information while going through at the database level.  Currently, I'm selecting an element by id and then running a macro that'll spit that info out, which works, but it's a slow process, especially if I'm trying to see things at the Document level.

**Comment by Nice3point** [comment]
Will be added in the next release

**Comment by Nice3point** [comment]
Implemented as an extension for the **Element** type
![изображение](https://github.com/jeremytammik/RevitLookup/assets/20504884/13fe87db-e2c9-4653-ae43-46047b8b2d54)

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/releases/tag/2025.0.8
