### ISSUE TITLE
2025.0.8 - Can't Load Assembly

### ISSUE THREAD

**Issue by ttiefenbach** [jeremytammik/RevitLookup#265]
After installing 2025.0.8, I get an error that RevitLookup can't load assembly "Nice3point.Revit.Toolkit."  It references version 2025.0.1.0, and that dll exists in the Addins\RevitLookup folder:
![image](https://github.com/jeremytammik/RevitLookup/assets/11864342/2a096963-88f3-4f09-82b6-990afe82a5b6)
![image](https://github.com/jeremytammik/RevitLookup/assets/11864342/30a12d4a-1d8b-48ad-8a9d-ffe93be4f1d9)

I tried both single-user and multi-user installers and both have the same message.

2025.0.7 works as expected.

**Comment by Nice3point** [comment]
@ttiefenbach https://github.com/jeremytammik/RevitLookup/releases/tag/2025.0.8

`Therefore, if your other plugins use Nice3point.Revit.Toolkit, it must be updated to version [2025.0.1](https://github.com/Nice3point/RevitToolkit/releases/tag/2025.0.1), which introduces this feature`

Probably you have an addin with an old version of Nice3point.Revit.Toolkit installed.
It's the only one restriction on the 2025 version

**Comment by ttiefenbach** [comment]
I found the offending addin and disabled it.  RevitLookup 2025.0.8 works as expected now.  Since I didn't create the other addin, I'll have to wait till that gets updated.  Thanks!
