### ISSUE TITLE
Missing quick access icon

### ISSUE THREAD

**Issue by Uetna** [jeremytammik/RevitLookup#267]
In recent versions, I noticed that the image on the quick access toolbar disappears. but the app is working
![image](https://github.com/user-attachments/assets/15e84175-165c-4073-8373-b9466188b6c2)
![image](https://github.com/user-attachments/assets/4e620094-6719-4e4a-9445-3dc9ce4d6993)

**Comment by Nice3point** [comment]
I'll take a look after vacation

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/issues/210 https://github.com/jeremytammik/RevitLookup/issues/252

Duplication of dependency conflicts

**Comment by jeremytammik** [comment]
> I'll take a look after vacation

i wish you a restful break and a wonderful time! i'll be away next week as well, bicycling in france.

**Comment by Nice3point** [comment]
> i wish you a restful break and a wonderful time! 

Thank you so much

> i'll be away next week as well, bicycling in france.

That sounds incredible! Have a great time Jeremy, I hope you have a full rest and a great time🪽

**Comment by vasilepandaciuc** [comment]
same issue here - please let me know if I can help in any way on fixing it
![image](https://github.com/user-attachments/assets/3603a147-e6c5-447d-ac09-bab41169f0c3)

**Comment by Hoss1831** [comment]
Same issue here on all revit versions
![image](https://github.com/user-attachments/assets/52ed4fcc-e9c7-4840-b176-df06c430bf1f)

**Comment by NeVeSpl** [comment]
You can always use [Revit database explorer](https://github.com/NeVeSpl/RevitDBExplorer) until problems with RevitLookup will get fixed. RDBE does not have any (reported) problems with dependencies.

**Comment by Nice3point** [comment]
@Hoss1831 @vasilepandaciuc  @Uetna  Please discuss only about missing icons in this thread. For dependency conflicts created a separate issue https://github.com/jeremytammik/RevitLookup/issues/269

**Comment by Nice3point** [comment]
Missing icon fixed and will be included in the next Release

**Comment by Nice3point** [comment]
Fixed in the 2025.0.9 update

**Comment by Uetna** [comment]
Thanks, checked on versions 21-24 works well
