### ISSUE TITLE
DataGrid Accent Color not working in dark theme

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#273]
### RevitLookup version

2025.0.8

### Steps to reproduce

By default RevitLookup uses the windows color as the Accent Color.

When using the dark theme, that color brightness is changed to make a better contrast in the dark background.

In the `DataGrid` the Accent Color brightness is not updated like the others UI elements.

If the windows system color is a dark color is really hard to visualize the data in the RevitLookup.

The image show when using a Dark Blue. `The box show the correct color and the wrong color apply in the DataGrid`

![image](https://github.com/user-attachments/assets/105ad182-7809-404d-9dc2-bb9653271ffa)

**Comment by Nice3point** [comment]
Fixed in the 2025.0.9 update. Color now synced with system

**Comment by ricaun** [comment]
> Fixed in the 2025.0.9 update. Color now synced with system

Great!

I noticed the `Nothing to show` and `Waiting for events` is black for some reason! That happen when RevitLookup is opened in dark theme.

![image](https://github.com/user-attachments/assets/cc3fc7e2-7af9-4cc3-ad3b-a9608fcfe3d8)

**Comment by Nice3point** [comment]
@ricaun no problems until version 25, need to look into what's wrong with resources:

![изображение](https://github.com/user-attachments/assets/40bd2b81-2de3-40b3-8c3c-8f1ec0f2ae43)

**Comment by ricaun** [comment]
I test with all the background effects and when I open a new RevitLookup always shows the text in black. I don't know if the background works because my windows version is 10.0.19045.

![image](https://github.com/user-attachments/assets/4dac5416-0e4a-426b-9b26-fe2c401a152b)

**Comment by ricaun** [comment]
New pr just in case. #291
