### ISSUE TITLE
Cannot install the extension

### ISSUE THREAD

**Issue by RalphMV1024** [jeremytammik/RevitLookup#275]
### RevitLookup version

RevitLookup-2022.3.8-SingleUser

### Steps to reproduce

Here is the screenshot of what message I got.
![image](https://github.com/user-attachments/assets/95a26a94-eb53-4307-b69b-15c0fbd67264)

**Comment by Nice3point** [comment]
https://github.com/jeremytammik/RevitLookup/issues/269

**Comment by RalphMV1024** [comment]
It is Revit 2022

**Comment by Nice3point** [comment]
You need to specify the third-party plugins you have installed besides RevitLookup

**Comment by RalphMV1024** [comment]
oh, I have CTC software, Ideate Software, Pollination by Ladybug Tools. let me try the earlier version

**Comment by RalphMV1024** [comment]
i did not see a 2022.3.7 but i did get it to work by using this
![image](https://github.com/user-attachments/assets/9d30a4e5-a39d-4807-a2d5-4f9cecf9978c)
from here:
https://github.com/jeremytammik/RevitLookup/releases/tag/2023.1.0-EOL

**Comment by Nice3point** [comment]
@RalphMV1024 can you run this tool and share the report file here?

 [DependenciesReport.zip](https://github.com/user-attachments/files/16808106/DependenciesReport.zip)

![изображение](https://github.com/user-attachments/assets/dab416fe-5531-4f13-9f14-4d8f51a33f9d)
![изображение](https://github.com/user-attachments/assets/3e3d363e-2bd6-4cb3-83b1-61c6b1e9a2c4)
