### ISSUE TITLE
Text 'Nothing to show' with wrong color in dark theme.

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#291]
### RevitLookup version

2025.0.9

### Steps to reproduce

I noticed the `Nothing to show` and `Waiting for events` is black for some reason! That happen when RevitLookup is opened in dark theme.

![image](https://github.com/user-attachments/assets/cc3fc7e2-7af9-4cc3-ad3b-a9608fcfe3d8)

I test with all the background effects and when I open a new RevitLookup always shows the text in black. I don't know if the background works because my windows version is 10.0.19045.

**Comment by Nice3point** [comment]
Fixed and will be included in the next hot fix
![изображение](https://github.com/user-attachments/assets/a5a98f4a-c4c1-4050-bf00-69c5fda7a1b7)
