### ISSUE TITLE
RevitRibbonControl non-public break main Ribbon.

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#292]
### RevitLookup version

2025.0.9

### Steps to reproduce

If the option `non-public` is enable in RevitLookup and you snoop the `Ribbon` inside the `Component manager` the main Revit ribbon stop working.

Here is a video: [RevitLookup - Snoop RevitRibbonControl breaks main Ribbon.](https://youtu.be/MgMBb16A7JY)

![RevitLookup - RevitRibbonControl](https://github.com/user-attachments/assets/7e89537b-1f47-4470-93aa-363983b7fe04)

I don't know yet what specific `non-public`  member in `RevitRibbonControl` that is breaking the UI, gonna make some tests later.

**Comment by Nice3point** [comment]
Most likely the private members contain a method or property that causes this glitch. Which does not return a value, but changes something in the normal behavior. The only thing to do is to figure out what the method is and forcibly disable it

**Comment by ricaun** [comment]
> Which does not return a value

The void methods is ignore right?

**Comment by ricaun** [comment]
> > The void methods is ignore right?
> 
> Yes, but we have a methods like `Focus()` that returns `bool`

The `Enter()` that returns `bool` breaks the UI.

```
[Transaction(TransactionMode.Manual)]
public class Command : IExternalCommand
{
    public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elementSet)
    {
        var ribbon = UIFramework.RevitRibbonControl.RibbonControl;
        var type = ribbon.GetType();
        var method = type.GetMethod("Enter", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance); // System.Windows.Media.Visual
        var result = method.Invoke(ribbon, null);
        Console.WriteLine($"{method} \t {result}");

        return Result.Succeeded;
    }
}
```

**Comment by ricaun** [comment]
Maybe the methods should be only executed if the use click, is related to this issue as well: [#239](https://github.com/jeremytammik/RevitLookup/issues/239)

**Comment by Nice3point** [comment]
Yes, I plan to take the Lookup engine out as a new project and develop it separately, it will be easier to test and implement such functionality. It will be possible to add Lazy evaluation and Force evaluation for similar cases

**Comment by Nice3point** [comment]
> > > The void methods is ignore right?
> > 
> > 
> > Yes, but we have a methods like `Focus()` that returns `bool`
> 
> The `Enter()` that returns `bool` breaks the UI.

Oh great, thanks for research 🎉
