### ISSUE TITLE
Revit Lookup doesn't snoop all members

### ISSUE THREAD

**Issue by htlcnn** [jeremytammik/RevitLookup#35]
I tried snooping a selected Structual Rebar element in the active view and found not all of the Rebar Class members showed up in the Snoop Objects window. One of many members that weren't there: Rebar.GetFulGeometryForView method.
Is this the supposed behaviour for Revit Lookup? I was thinking I could get all object members with Revit Lookup and without RevitAPI.chm file.

**Comment by jeremytammik** [comment]
Do you mean **GetFullGeometryForView**? There is no guarantee that RevitLookup will be able to report **all** properties and methods on **all** elements. For instance, in the case of GetFullGeometryForView, a view input argument is required. How is RevitLookup supposed to be able to guess what view you are interested in? For methods requiring dynamic input that cannot be automatically determined, you will have to make use of more intimate interactive database exploration tools, e.g. RevitPythonShell: http://thebuildingcoder.typepad.com/blog/2013/11/intimate-revit-database-exploration-with-the-python-shell.html.
