### ISSUE TITLE
ConvertToStableRepresentation for Reference

### ISSUE THREAD

**Issue by Pekshev** [jeremytammik/RevitLookup#40]
Please add ConvertToStableRepresentation() method for References

**Comment by jeremytammik** [comment]
good idea. would you like to implement it and submit a pull request? thank you!

**Comment by Pekshev** [comment]
I’m trying

**Comment by Pekshev** [comment]
It seems I did it =)
![screenshot_5](https://user-images.githubusercontent.com/12638819/36866939-c892ad32-1da4-11e8-94f1-3a8f0dbfe11d.png)

Now we need to figure out how to do the Pull Request (I never did it)
Perhaps you will find a more elegant solution

**Comment by jeremytammik** [comment]
well done, looks like a very clean solution! thank you!
