### ISSUE TITLE
where is

### ISSUE THREAD

**Issue by raydied4** [jeremytammik/RevitLookup#44]

**Comment by raydied4** [comment]
where is the RevitLookup.dll?
How can i install the revitlookup?
please

**Comment by andydandy74** [comment]
You'll either have to build it yourself in Visual Studio or download it from here: https://lookupbuilds.com/index.html?prefix=releases/

**Comment by jeremytammik** [comment]
hey andy, thank you very much for jumping in and answering! you were super quick and to the point!
