### ISSUE TITLE
Center parent for forms

### ISSUE THREAD

**Issue by TheKidMSX** [jeremytammik/RevitLookup#45]
I have a little request. Could you please change all forms startposition to "CenterParent". I must change that everytime I download a new build. When working with 2 screens, revitlookup manages to show it's dialogs on the wrong screen (or half outside the screen).

**Comment by jeremytammik** [comment]
yes, of course, with pleasure. please fork the repo, make the changes you always make, commit the changes, and submit a pull request for me to integrate them into the main repo. thank you!

**Comment by jeremytammik** [comment]
no, it seems it is not correct. i pulled your push and integrated it into my stream. that produced new modules in the main top-level directory:
```
BindingMap.cs		Geometry.cs		ParamEnumSnoop.cs
Categories.cs		ObjTreeBase.cs		Parameters.cs
EventsForm.cs		Objects.cs		SearchBy.Designer.cs
EventsForm.designer.cs	ParamEnum.Designer.cs	SearchBy.cs
GenericPropGrid.cs	ParamEnum.cs
```
Before the pull, the top-level directory only contained this:
```
CS		LICENSE		README.md	Wishlist.md
```

**Comment by jeremytammik** [comment]
i don't know what you changed where. for instance, `BindingMap.cs` exists in two places, plus now your third:
```
/v/C/a/vs/RevitLookup $ find . | grep  BindingMap.cs
./BindingMap.cs
./CS/Snoop/Data/BindingMap.cs
./CS/Snoop/Forms/BindingMap.cs
```

**Comment by jeremytammik** [comment]
ok, it seems they all belong in `CS/EventTrack/Forms`

**Comment by jeremytammik** [comment]
no, most go into `CS/Snoop/Forms`.

**Comment by jeremytammik** [comment]
ok, i managed it. integrated into version 2019.0.0.3

**Comment by TheKidMSX** [comment]
Any Idea what I did wrong (to prevent futher commit problems) ?

**Comment by jeremytammik** [comment]
nope. sorry, no idea. better luck next time  :-)
