### ISSUE TITLE
The MSI in the project is flawed

### ISSUE THREAD

**Issue by VBScab** [jeremytammik/RevitLookup#51]
The MSI installer contains a bunch of unnecessary "fluff". Just one example is that it ends up creating a spurious folder '%AppData%\Autodesk\revit\Addins\2014\'.

Given that this add-in comprises just 2 files and that the target folder is always the same, I built a much more streamlined one which I'm happy to share with you: https://1drv.ms/u/s!ArqlqZQvQnGihpkT9yDhfippM8_Krw

**Comment by jeremytammik** [comment]
thank you very much. this project does not include any installer, or any binary files at all, for that matter. where did you see the other installer you mention with all the fluff? what exact release of RevitLookup does your installer contain?

**Comment by VBScab** [comment]
Hi, Jeremy

 

Whilst I appreciate that the project itself doesn’t contain an installer, on the page https://github.com/jeremytammik/RevitLookup this text appears:

 

[quote]

Harry Mattison of  <https://boostyourbim.wordpress.com/> Boost your BIM very kindly provides a ready-built  <https://boostyourbim.wordpress.com/2017/04/28/revit-lookup-2018-install> RevitLookup 2018 installer:

If you don’t want to deal with source code and just want to use the tool, here is  <https://drive.google.com/open?id=182W00Mk5Hj1FMHAo-xVnoFYlJ_s2Swrw> Revit Lookup 2018.msi, an installer for the compiled and signed DLL ready, courtesy of Boost Your BIM.

 

[/quote]

 

That looks like a binary installer to me 😊

 

My MSI contains whatever the fluffy one does, just without the fluff, viz: v2018.0.0. I have even reproduced the original MSI’s erroneous version number (the ‘ProductVersion’ property) of ‘1.0.0’.

 

Kind regards,

Ian

**Comment by jeremytammik** [comment]
Thank you for the clarification! I understand and agree, and thank you again for sharing your cleaned up installer. What version is it exactly? Above, you say v2018.0.0. However, the RevitLookup releases are numbered according to the major.minor.build.revision convention, so the last digit is missing from your answer. May I assume it is a zero, i.e., v2018.0.0.0? Thanks!

**Comment by VBScab** [comment]
OK, I’ve just uploaded a revision which is versioned 2018.0.0.0 and updated the OneDrive link.

 

Cheers!

**Comment by jeremytammik** [comment]
Thank you, I added it to the repository now and updated the readme to explain.
