### ISSUE TITLE
about geometry transform

### ISSUE THREAD

**Issue by xierunhua** [jeremytammik/RevitLookup#54]
`private void Getinfo_Room(Room room)
{
    string message = "Room: ";

    //get the name of the room
    message += "\nRoom Name: " + room.Name;

    //get the room position
    LocationPoint location = room.Location as LocationPoint;
    XYZ point = location.Point;
    message += "\nRoom position: " + XYZToString(point);

    //get the room number
    message += "\nRoom number: " + room.Number;

    IList<IList<Autodesk.Revit.DB.BoundarySegment>> segments = room.GetBoundarySegments(new SpatialElementBoundaryOptions());
    if (null != segments)  //the room may not be bound
    {
        foreach (IList<Autodesk.Revit.DB.BoundarySegment> segmentList in segments)
        {
            message += "\nBoundarySegment of the room: ";
            foreach (Autodesk.Revit.DB.BoundarySegment boundarySegment in segmentList)
            {
                // Get curve start point
                XYZ start = boundarySegment.GetCurve().GetEndPoint(0);
                message += "\nCurve start point: " + XYZToString(start);
                // Get curve end point
                XYZ end = boundarySegment.GetCurve().GetEndPoint(1);
                message += " Curve end point: " + XYZToString(end);

                // Show the boundary elements
                message += "\nBoundary element id: " + boundarySegment.ElementId.IntegerValue;
            }
        }
    }

    TaskDialog.Show("Revit",message);
}

// output the point's three coordinates
string XYZToString(XYZ point)
{
    return "(" + point.X + ", " + point.Y + ", " + point.Z + ")";
}
`

This is sample code. But I want to get the real world position. I have set the real north in REVIT 2018. 
So, what should I do in my code?

**Comment by xierunhua** [comment]
I want to get the truth north XYZ, but not the project north XYZ.

**Comment by jeremytammik** [comment]
Why are you posting this as an issue with RevitLookup? It is not related to RevitLookup afaict. Please post a query in the Revit API discussion forum instead. Thank you! -- https://forums.autodesk.com/t5/revit-api-forum/bd-p/160
