### ISSUE TITLE
Clicking on PrintManager sends document to printer

### ISSUE THREAD

**Issue by RyanSchw** [jeremytammik/RevitLookup#55]
I was snooping the current document in Revit 2019, and when I clicked on the "PrintManager" field it sent my document to the printer.

**Comment by jeremytammik** [comment]
Wow. Can you take a look in the debugger and determine what might be causing that? Thank you!

**Comment by kelicto** [comment]
Some time ago I found this question, I think this question is not important. But, I would like do it.

**Comment by jeremytammik** [comment]
Well, I imagine it is not hard to do. All you need to do is presumably to invoke the [`SubmitPrint` method](https://www.revitapidocs.com/2020/0c9524b7-33b5-8c76-2843-c7024f03e4d7.htm).

**Comment by CADBIMDeveloper** [comment]
Hey! Take a look at RevitLookup.Snoop.CollectorExts.DataFactory class, there is a sample of preventing method invocation:

>             if (declaringType == typeof (Document) && methodInfo.Name == nameof(Document.Close))
                return null;


Just do the same for SubmitPrint method

**Comment by kelicto** [comment]
Can I ask you a question? How to hide the toolbar below the editor tab or other tab? Think you!


At 2019-10-04 17:47:04, "Alexander Ignatovich" <notifications@github.com> wrote:


Hey! Take a look at RevitLookup.Snoop.CollectorExts.DataFactory class, there is a sample of preventing method invocation:

        if (declaringType == typeof (Document) && methodInfo.Name == nameof(Document.Close))

            return null;


Just do the same for SubmitPrint method

**Comment by kelicto** [comment]
Can I ask you a question? How to hide the toolbar below the tab. Please see attachment, Think you!





At 2019-10-04 17:36:07, "Jeremy Tammik" <notifications@github.com> wrote:


Well, I imagine it is not hard to do. All you need to do is presumably to invoke the SubmitPrint method.

**Comment by jeremytammik** [comment]
@kelicto please do not ask unrelated questions here. If you have an issue with RevitLookup, submit a new issue for it. Please submit all other questions to the Revit API discussion forum. Please search for existing answers before posting any new questions.

**Comment by kelicto** [comment]
I am sorry. When I sent this message, I used web email box.

**Comment by jeremytammik** [comment]
@CADBIMDeveloper cleaning up... would you like to implement the code to suppress the SubmitPrint method call? Thx!
