### ISSUE TITLE
2 questions about Lookup 2018

### ISSUE THREAD

**Issue by keleisi2001** [jeremytammik/RevitLookup#60]
Recently I installed Revit Lookup, there are two questions.

1. After clicking the lookup button, there will be some options starting with Snoop. What do these snoop stand for? Is there an official document?
![1](https://user-images.githubusercontent.com/55388367/85369537-d8ada280-b55f-11ea-8148-9bb0b221ad42.png)

2. 2. After clicking these buttons, a large amount of information is given in the form of a structured list. Some of this information is relatively easy to understand but someone is difficult to understand. Is there a complete explanation to tell the user the meaning of each information?

![2](https://user-images.githubusercontent.com/55388367/85370544-73f34780-b561-11ea-85a8-fb3222db6669.png)

**Comment by jeremytammik** [comment]
You can look up the meaning of the word 'snoop' in an English dictionary: 

https://duckduckgo.com/?q=snoop

The Revit API classes and their properties are documented in the Revit API help file in the Revit SDK, also available online:

https://www.revitapidocs.com

Before asking any further questions, please work through the Revit API getting started material and the further documentation pointed out there:

https://thebuildingcoder.typepad.com/blog/about-the-author.html#2
