### ISSUE TITLE
ScheduleDefinition.GetField method not showing

### ISSUE THREAD

**Issue by RevitArkitek** [jeremytammik/RevitLookup#70]
The method ScheduleDefinition.GetField does not show because it requires an integer index parameter.  A list of ScheduleFields can be returned, named by the index that was used.

I have this working and can submit a pull request.  I have an issue though, in that there are two GetField methods, the other taking in an id.  I have not found a way to filter out the second method, so when viewing the ScheduleDefinition properties there will be two GetField entries.  If you know of a way to filter out that second method you can let me know or you could add it.  Otherwise it could be left as is or put on hold.

**Comment by jeremytammik** [comment]
That sounds great, very useful! 

Thank you very much for the offer!

That would require analysing the complete `GetField` method signature. 

The two overloads `GetField(Int32)` and `GetField(ScheduleFieldId)` have different method signatures:

https://www.c-sharpcorner.com/UploadFile/puranindia/method-signatures-in-C-Sharp/

They can be distinguished using by checking their parameter types using `Reflection`, as explained in how to get only methods with a specific signature out of `Type.GetMethods`:

https://stackoverflow.com/questions/5152346/get-only-methods-with-specific-signature-out-of-type-getmethods

**Comment by RevitArkitek** [comment]
Sent pull request.

**Comment by jeremytammik** [comment]
Thank you, merging now.

**Comment by jeremytammik** [comment]
Integrated in https://github.com/jeremytammik/RevitLookup/releases/tag/2021.0.0.13
