### ISSUE TITLE
Multi-version support for Revit 2016-2022 

### ISSUE THREAD

**Issue by jeremytammik** [jeremytammik/RevitLookup#79]
Hi Jeremy,

I see that the multi-version configurations that I submitted to RevitLookup were undone by a recent submission. I'd be happy to build a new multi-version installer for Revit 2016-2022 (or whatever versions people would like), but I'm not sure how you'd like the solution configured to do this. Could you let me know?

Thanks
Harry

**Comment by peterhirn** [comment]
Hi,

I recommend using a solution setup like this https://github.com/Autodesk-Forge/design.automation-csharp-revit.local.debug.tool if you want to add multi-version support.

On the other hand this seems completely unnecessary, since eg. Revit 2020 will happily load the latest version of Lookup 2022. I'm using it daily.

Best regards

**Comment by harrymattison** [comment]
Does it support earlier versions? I saw at least one reference to
ForgeTypeId in the code which didn't exist in the API a few years ago.

**Comment by peterhirn** [comment]
Good point, there is actually a problem with `ForgeTypeId` used here https://github.com/jeremytammik/RevitLookup/blob/90ad180101bdc05d8450aa224d6a13b073dc9cdf/CS/Snoop/CollectorExts/ExtensibleStorageEntityContentStream.cs#L156

Opening extensible storage is therefore not possible in versions < 2021 and throws an exception. This would need to be handled in a multi-version setup.

My main concern is `RevitAPI.dll` et al. references. They are obviously required to build and need to be made available for the CI. This is currently done by downloading them on the fly, which is a hack I'd like to get rid of.

@jeremytammik any updates on Revit nuget packages? ;)

The other option is to add them directly to this repository using LFS. With multi-version support we would need to add all required dlls for all supported versions.

Overall I think it's not worth the effort. Users can download Lookup for their specific Revit version from https://lookupbuilds.com all the way back to 2015. Sure, they don't get the latest features/bugfixes but they are also using a out-of-date Revit.

I think Jeremy should make the call which versions should be supported and what should be build/released with the CI. In my opinion supporting only the latest Revit version is good enough.

**Comment by jeremytammik** [comment]
I'm OK with supporting only the latest version and agree that the other options for previous release support are sufficient.
