### ISSUE TITLE
Errors during Build

### ISSUE THREAD

**Issue by anagnam** [jeremytammik/RevitLookup#8]
Hi Jeremy,
Upon building the solution file, I found 7 errors. Any hint as to how to solve this issue?
![err](https://cloud.githubusercontent.com/assets/514966/7236691/1517e878-e79f-11e4-9653-68a14105595f.JPG)

**Comment by jeremytammik** [comment]
it looks as if you are compiling the Revit 2015 code using the Revit 2016 API assemblies.

please wait a couple of days until we can publish the updated code for Revit 2016.

**Comment by anagnam** [comment]
yes, I did use the 2016 API assemblies to compile. 
I will wait for the updated code for 2016 then. Thank you.

**Comment by jeremytammik** [comment]
check out the new release: https://github.com/jeremytammik/RevitLookup/releases/tag/2016.0.0.6
