### ISSUE TITLE
dll certificate expired?

### ISSUE THREAD

**Issue by marcsirl** [jeremytammik/RevitLookup#82]
Hello!  I just started noticing that Revit is prompting about unsigned certificate for this add-in (all Revit versions 2018-2021).  Checked the dll for the latest release and it appears the cert may have expired this month.

**Comment by jeremytammik** [comment]
who issued that certificate?

**Comment by marcsirl** [comment]
The certificate used to sign code on this add-in.

![image](https://user-images.githubusercontent.com/17609519/120591734-fd084380-c47f-11eb-87e6-f71646b8ba6c.png)

**Comment by jeremytammik** [comment]
Aha. Thank you. The certificate is from Harry Mattison of Boost Your BIM, @harrymattison

**Comment by jeremytammik** [comment]
This issue has nothing to do with the RevitLookup per se, only the Boost you Bim installer. There is nothing I can do to fix that. Please contact Boost your BIM about the issue.
