### ISSUE TITLE
RevitLookup.Installation

### ISSUE THREAD

**Issue by ricaun** [jeremytammik/RevitLookup#87]
Hey Jeremy!

I created a simple Installation using [Inno Setup](http://www.jrsoftware.org/isinfo.php) to extract the files on the ApplicationPlugins folder.

Here is the project: [RevitLookup.Installation](https://github.com/ricaun/RevitLookup.Installation)

And the last Executable Signed: [RevitLookup.2022.0.0.14](https://github.com/ricaun/RevitLookup.Installation/releases/download/2022.0.0.14/RevitLookup.2022.0.0.14.zip) with the version 2017 to 2022.

I hope this helps the community! 

See ya!

**Comment by jeremytammik** [comment]
Brilliant idea, implementing the installation as a separate project. Very effective solution and useful sample! Thank you very much!

**Comment by jeremytammik** [comment]
Thank you very much again for the cool project. I added a note of it and a link to the RevitLookup readme: 

https://github.com/jeremytammik/RevitLookup#revitlookupinstallation
