### ISSUE TITLE
installation for Revit 2022

### ISSUE THREAD

**Issue by matejonas** [jeremytammik/RevitLookup#89]
Hi all,

I tried to install RevitLookup for Revit 2022 using 'Revit Lookup.msi' which within the RevitLookup-2022.0.0.15.zip file. The addin will appear in earlier Revit versions, but not in 2022, it will not create the .dll and .addin files in the appropriate folder.
Does anyone have any idea why the two files are not installed in the correct folder?
Or where can I find these two files inside the zip?
![image](https://user-images.githubusercontent.com/88876742/130613949-05653532-3b57-41b5-a163-1176539122e2.png)

Thank you for your help,
Máté

**Comment by jeremytammik** [comment]
Oh dear, I am no knowledgeable at all with the installer. As you have noticed, all you need to do is manually copy the `DLL` (.NET assembly) and `addin` (manifest file) to the appropriate Revit `AddIns` folder. I cannot say why the `MSI` is not automatically doing so, though.

**Comment by jeremytammik** [comment]
Maybe @peterhirn can help?

**Comment by peterhirn** [comment]
Hi. The installer (msi) is afaik not maintained by anyone. Maybe it should be removed from the repository? We could add a WiX (https://wixtoolset.org/) script to the repo and build installers with the CI at some point. I don't have enough spare time for this at the moment. ;)

Please download the latest version from https://lookupbuilds.com and unzip/install as described by @jeremytammik above.

**Comment by jeremytammik** [comment]
Aha. Good. Thank you very much for the explanation. Yes, I agree, I should remove the `msi`, or at least make it obvious that it is not current and not maintained.

**Comment by matejonas** [comment]
ahh, great, i didn't know this page (https://lookupbuilds.com), i always downloaded msi from github and installed it, but from now on this page will be my home page :D
thank you very much for your help
