### ISSUE TITLE
Revit lookup 2020 - Not installing

### ISSUE THREAD

**Issue by mpguru66** [jeremytammik/RevitLookup#90]
Hi Jeremy, I've installed 2020's +thumbs up+ but running the 2022 Revit Lookup-SetupFiles > Revit Lookup.msi installer isn't adding lookup to 2022. Any thoughts?
![20](https://user-images.githubusercontent.com/15841114/132546394-da680b4c-e0ed-40d3-98e6-23a77d51accb.jpg)
![22](https://user-images.githubusercontent.com/15841114/132546397-fbeb2f2d-d99d-4fe5-a879-6c076cd36dce.jpg)

**Comment by jeremytammik** [comment]
Yes. Use the prebuilt build instead: https://github.com/jeremytammik/RevitLookup#-builds

**Comment by mpguru66** [comment]
> Yes. Use the prebuilt build instead: https://github.com/jeremytammik/RevitLookup#-builds

Got it. Many thanks 👍👍

**Comment by jeremytammik** [comment]
no problem :-)
